/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./networkmanager-qt/src/dbus/introspection/nm-agent-manager.xml -a ./networkmanager-qt/toolGenerate/qdbusxml2cpp/nm-agent-managerAdaptor -i ./networkmanager-qt/toolGenerate/qdbusxml2cpp/nm-agent-manager.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef NM-AGENT-MANAGERADAPTOR_H
#define NM-AGENT-MANAGERADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./networkmanager-qt/toolGenerate/qdbusxml2cpp/nm-agent-manager.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.freedesktop.NetworkManager.AgentManager
 */
class AgentManagerAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.freedesktop.NetworkManager.AgentManager")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.freedesktop.NetworkManager.AgentManager\">\n"
"    <method name=\"Register\">\n"
"      <annotation value=\"impl_agent_manager_register\" name=\"org.freedesktop.DBus.GLib.CSymbol\"/>\n"
"      <annotation value=\"\" name=\"org.freedesktop.DBus.GLib.Async\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"identifier\"/>\n"
"    </method>\n"
"    <method name=\"RegisterWithCapabilities\">\n"
"      <annotation value=\"impl_agent_manager_register_with_capabilities\" name=\"org.freedesktop.DBus.GLib.CSymbol\"/>\n"
"      <annotation value=\"\" name=\"org.freedesktop.DBus.GLib.Async\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"identifier\"/>\n"
"      <arg direction=\"in\" type=\"u\" name=\"capabilities\"/>\n"
"    </method>\n"
"    <method name=\"Unregister\">\n"
"      <annotation value=\"impl_agent_manager_unregister\" name=\"org.freedesktop.DBus.GLib.CSymbol\"/>\n"
"      <annotation value=\"\" name=\"org.freedesktop.DBus.GLib.Async\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    AgentManagerAdaptor(QObject *parent);
    virtual ~AgentManagerAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void Register(const QString &identifier);
    void RegisterWithCapabilities(const QString &identifier, uint capabilities);
    void Unregister();
Q_SIGNALS: // SIGNALS
};

#endif
