/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./networkmanager-qt/src/dbus/introspection/org.freedesktop.NetworkManager.VPN.Plugin.xml -a ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.VPN.PluginAdaptor -i ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.VPN.Plugin.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.VPN.PluginAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class PluginAdaptor
 */

PluginAdaptor::PluginAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

PluginAdaptor::~PluginAdaptor()
{
    // destructor
}

uint PluginAdaptor::state() const
{
    // get the value of property State
    return qvariant_cast< uint >(parent()->property("State"));
}

void PluginAdaptor::Connect(NMVariantMapMap connection)
{
    // handle method call org.freedesktop.NetworkManager.VPN.Plugin.Connect
    QMetaObject::invokeMethod(parent(), "Connect", Q_ARG(NMVariantMapMap, connection));
}

void PluginAdaptor::ConnectInteractive(NMVariantMapMap connection, NMVariantMap details)
{
    // handle method call org.freedesktop.NetworkManager.VPN.Plugin.ConnectInteractive
    QMetaObject::invokeMethod(parent(), "ConnectInteractive", Q_ARG(NMVariantMapMap, connection), Q_ARG(NMVariantMap, details));
}

void PluginAdaptor::Disconnect()
{
    // handle method call org.freedesktop.NetworkManager.VPN.Plugin.Disconnect
    QMetaObject::invokeMethod(parent(), "Disconnect");
}

QString PluginAdaptor::NeedSecrets(NMVariantMapMap settings)
{
    // handle method call org.freedesktop.NetworkManager.VPN.Plugin.NeedSecrets
    QString setting_name;
    QMetaObject::invokeMethod(parent(), "NeedSecrets", Q_RETURN_ARG(QString, setting_name), Q_ARG(NMVariantMapMap, settings));
    return setting_name;
}

void PluginAdaptor::NewSecrets(NMVariantMapMap connection)
{
    // handle method call org.freedesktop.NetworkManager.VPN.Plugin.NewSecrets
    QMetaObject::invokeMethod(parent(), "NewSecrets", Q_ARG(NMVariantMapMap, connection));
}

void PluginAdaptor::SetConfig(NMVariantMap config)
{
    // handle method call org.freedesktop.NetworkManager.VPN.Plugin.SetConfig
    QMetaObject::invokeMethod(parent(), "SetConfig", Q_ARG(NMVariantMap, config));
}

void PluginAdaptor::SetFailure(const QString &reason)
{
    // handle method call org.freedesktop.NetworkManager.VPN.Plugin.SetFailure
    QMetaObject::invokeMethod(parent(), "SetFailure", Q_ARG(QString, reason));
}

void PluginAdaptor::SetIp4Config(NMVariantMap config)
{
    // handle method call org.freedesktop.NetworkManager.VPN.Plugin.SetIp4Config
    QMetaObject::invokeMethod(parent(), "SetIp4Config", Q_ARG(NMVariantMap, config));
}

void PluginAdaptor::SetIp6Config(NMVariantMap config)
{
    // handle method call org.freedesktop.NetworkManager.VPN.Plugin.SetIp6Config
    QMetaObject::invokeMethod(parent(), "SetIp6Config", Q_ARG(NMVariantMap, config));
}

