/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./networkmanager-qt/src/dbus/introspection/org.freedesktop.NetworkManager.Settings.Connection.xml -a ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Settings.ConnectionAdaptor -i ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Settings.Connection.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Settings.ConnectionAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class ConnectionAdaptor
 */

ConnectionAdaptor::ConnectionAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

ConnectionAdaptor::~ConnectionAdaptor()
{
    // destructor
}

bool ConnectionAdaptor::unsaved() const
{
    // get the value of property Unsaved
    return qvariant_cast< bool >(parent()->property("Unsaved"));
}

void ConnectionAdaptor::ClearSecrets()
{
    // handle method call org.freedesktop.NetworkManager.Settings.Connection.ClearSecrets
    QMetaObject::invokeMethod(parent(), "ClearSecrets");
}

void ConnectionAdaptor::Delete()
{
    // handle method call org.freedesktop.NetworkManager.Settings.Connection.Delete
    QMetaObject::invokeMethod(parent(), "Delete");
}

NMVariantMapMap ConnectionAdaptor::GetSecrets(const QString &setting_name)
{
    // handle method call org.freedesktop.NetworkManager.Settings.Connection.GetSecrets
    NMVariantMapMap secrets;
    QMetaObject::invokeMethod(parent(), "GetSecrets", Q_RETURN_ARG(NMVariantMapMap, secrets), Q_ARG(QString, setting_name));
    return secrets;
}

NMVariantMapMap ConnectionAdaptor::GetSettings()
{
    // handle method call org.freedesktop.NetworkManager.Settings.Connection.GetSettings
    NMVariantMapMap settings;
    QMetaObject::invokeMethod(parent(), "GetSettings", Q_RETURN_ARG(NMVariantMapMap, settings));
    return settings;
}

void ConnectionAdaptor::Save()
{
    // handle method call org.freedesktop.NetworkManager.Settings.Connection.Save
    QMetaObject::invokeMethod(parent(), "Save");
}

void ConnectionAdaptor::Update(NMVariantMapMap properties)
{
    // handle method call org.freedesktop.NetworkManager.Settings.Connection.Update
    QMetaObject::invokeMethod(parent(), "Update", Q_ARG(NMVariantMapMap, properties));
}

void ConnectionAdaptor::UpdateUnsaved(NMVariantMapMap properties)
{
    // handle method call org.freedesktop.NetworkManager.Settings.Connection.UpdateUnsaved
    QMetaObject::invokeMethod(parent(), "UpdateUnsaved", Q_ARG(NMVariantMapMap, properties));
}

