/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./networkmanager-qt/src/dbus/introspection/org.freedesktop.NetworkManager.Device.Macvlan.xml -a ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.MacvlanAdaptor -i ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.Macvlan.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.MacvlanAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class MacvlanAdaptor
 */

MacvlanAdaptor::MacvlanAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

MacvlanAdaptor::~MacvlanAdaptor()
{
    // destructor
}

QString MacvlanAdaptor::mode() const
{
    // get the value of property Mode
    return qvariant_cast< QString >(parent()->property("Mode"));
}

bool MacvlanAdaptor::noPromisc() const
{
    // get the value of property NoPromisc
    return qvariant_cast< bool >(parent()->property("NoPromisc"));
}

QDBusObjectPath MacvlanAdaptor::parent() const
{
    // get the value of property Parent
    return qvariant_cast< QDBusObjectPath >(parent()->property("Parent"));
}

bool MacvlanAdaptor::tap() const
{
    // get the value of property Tap
    return qvariant_cast< bool >(parent()->property("Tap"));
}

