/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./networkmanager-qt/src/dbus/introspection/org.freedesktop.NetworkManager.Device.WiMax.xml -a ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.WiMaxAdaptor -i ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.WiMax.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.WiMaxAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class WiMaxAdaptor
 */

WiMaxAdaptor::WiMaxAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

WiMaxAdaptor::~WiMaxAdaptor()
{
    // destructor
}

QDBusObjectPath WiMaxAdaptor::activeNsp() const
{
    // get the value of property ActiveNsp
    return qvariant_cast< QDBusObjectPath >(parent()->property("ActiveNsp"));
}

QString WiMaxAdaptor::bsid() const
{
    // get the value of property Bsid
    return qvariant_cast< QString >(parent()->property("Bsid"));
}

uint WiMaxAdaptor::centerFrequency() const
{
    // get the value of property CenterFrequency
    return qvariant_cast< uint >(parent()->property("CenterFrequency"));
}

int WiMaxAdaptor::cinr() const
{
    // get the value of property Cinr
    return qvariant_cast< int >(parent()->property("Cinr"));
}

QString WiMaxAdaptor::hwAddress() const
{
    // get the value of property HwAddress
    return qvariant_cast< QString >(parent()->property("HwAddress"));
}

QList<QDBusObjectPath> WiMaxAdaptor::nsps() const
{
    // get the value of property Nsps
    return qvariant_cast< QList<QDBusObjectPath> >(parent()->property("Nsps"));
}

int WiMaxAdaptor::rssi() const
{
    // get the value of property Rssi
    return qvariant_cast< int >(parent()->property("Rssi"));
}

int WiMaxAdaptor::txPower() const
{
    // get the value of property TxPower
    return qvariant_cast< int >(parent()->property("TxPower"));
}

QList<QDBusObjectPath> WiMaxAdaptor::GetNspList()
{
    // handle method call org.freedesktop.NetworkManager.Device.WiMax.GetNspList
    QList<QDBusObjectPath> nsps;
    QMetaObject::invokeMethod(parent(), "GetNspList", Q_RETURN_ARG(QList<QDBusObjectPath>, nsps));
    return nsps;
}

