/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./networkmanager-qt/src/dbus/introspection/org.freedesktop.NetworkManager.AccessPoint.xml -a ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.AccessPointAdaptor -i ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.AccessPoint.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.AccessPointAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class AccessPointAdaptor
 */

AccessPointAdaptor::AccessPointAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

AccessPointAdaptor::~AccessPointAdaptor()
{
    // destructor
}

uint AccessPointAdaptor::flags() const
{
    // get the value of property Flags
    return qvariant_cast< uint >(parent()->property("Flags"));
}

uint AccessPointAdaptor::frequency() const
{
    // get the value of property Frequency
    return qvariant_cast< uint >(parent()->property("Frequency"));
}

QString AccessPointAdaptor::hwAddress() const
{
    // get the value of property HwAddress
    return qvariant_cast< QString >(parent()->property("HwAddress"));
}

int AccessPointAdaptor::lastSeen() const
{
    // get the value of property LastSeen
    return qvariant_cast< int >(parent()->property("LastSeen"));
}

uint AccessPointAdaptor::maxBitrate() const
{
    // get the value of property MaxBitrate
    return qvariant_cast< uint >(parent()->property("MaxBitrate"));
}

uint AccessPointAdaptor::mode() const
{
    // get the value of property Mode
    return qvariant_cast< uint >(parent()->property("Mode"));
}

uint AccessPointAdaptor::rsnFlags() const
{
    // get the value of property RsnFlags
    return qvariant_cast< uint >(parent()->property("RsnFlags"));
}

QByteArray AccessPointAdaptor::ssid() const
{
    // get the value of property Ssid
    return qvariant_cast< QByteArray >(parent()->property("Ssid"));
}

uchar AccessPointAdaptor::strength() const
{
    // get the value of property Strength
    return qvariant_cast< uchar >(parent()->property("Strength"));
}

uint AccessPointAdaptor::wpaFlags() const
{
    // get the value of property WpaFlags
    return qvariant_cast< uint >(parent()->property("WpaFlags"));
}

