/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./networkmanager-qt/src/dbus/introspection/org.freedesktop.NetworkManager.IP4Config.xml -a ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.IP4ConfigAdaptor -i ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.IP4Config.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ORG_FREEDESKTOP_NETWORKMANAGER_IP4CONFIGADAPTOR_H
#define ORG_FREEDESKTOP_NETWORKMANAGER_IP4CONFIGADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.IP4Config.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.freedesktop.NetworkManager.IP4Config
 */
class IP4ConfigAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.freedesktop.NetworkManager.IP4Config")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.freedesktop.NetworkManager.IP4Config\">\n"
"    <property access=\"read\" type=\"aau\" name=\"Addresses\">\n"
"      <annotation value=\"UIntListList\" name=\"org.qtproject.QtDBus.QtTypeName\"/>\n"
"    </property>\n"
"    <property access=\"read\" type=\"aa{sv}\" name=\"AddressData\">\n"
"      <annotation value=\"NMVariantMapList\" name=\"org.qtproject.QtDBus.QtTypeName\"/>\n"
"    </property>\n"
"    <property access=\"read\" type=\"s\" name=\"Gateway\"/>\n"
"    <property access=\"read\" type=\"aau\" name=\"Routes\">\n"
"      <annotation value=\"UIntListList\" name=\"org.qtproject.QtDBus.QtTypeName\"/>\n"
"    </property>\n"
"    <property access=\"read\" type=\"aa{sv}\" name=\"RouteData\">\n"
"      <annotation value=\"NMVariantMapList\" name=\"org.qtproject.QtDBus.QtTypeName\"/>\n"
"    </property>\n"
"    <property access=\"read\" type=\"au\" name=\"Nameservers\">\n"
"      <annotation value=\"UIntList\" name=\"org.qtproject.QtDBus.QtTypeName\"/>\n"
"    </property>\n"
"    <property access=\"read\" type=\"as\" name=\"Domains\"/>\n"
"    <property access=\"read\" type=\"as\" name=\"Searches\"/>\n"
"    <property access=\"read\" type=\"as\" name=\"DnsOptions\"/>\n"
"    <property access=\"read\" type=\"i\" name=\"DnsPriority\"/>\n"
"    <property access=\"read\" type=\"au\" name=\"WinsServers\">\n"
"      <annotation value=\"UIntList\" name=\"org.qtproject.QtDBus.QtTypeName\"/>\n"
"    </property>\n"
"    <signal name=\"PropertiesChanged\">\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    IP4ConfigAdaptor(QObject *parent);
    virtual ~IP4ConfigAdaptor();

public: // PROPERTIES
    Q_PROPERTY(NMVariantMapList AddressData READ addressData)
    NMVariantMapList addressData() const;

    Q_PROPERTY(UIntListList Addresses READ addresses)
    UIntListList addresses() const;

    Q_PROPERTY(QStringList DnsOptions READ dnsOptions)
    QStringList dnsOptions() const;

    Q_PROPERTY(int DnsPriority READ dnsPriority)
    int dnsPriority() const;

    Q_PROPERTY(QStringList Domains READ domains)
    QStringList domains() const;

    Q_PROPERTY(QString Gateway READ gateway)
    QString gateway() const;

    Q_PROPERTY(UIntList Nameservers READ nameservers)
    UIntList nameservers() const;

    Q_PROPERTY(NMVariantMapList RouteData READ routeData)
    NMVariantMapList routeData() const;

    Q_PROPERTY(UIntListList Routes READ routes)
    UIntListList routes() const;

    Q_PROPERTY(QStringList Searches READ searches)
    QStringList searches() const;

    Q_PROPERTY(UIntList WinsServers READ winsServers)
    UIntList winsServers() const;

public Q_SLOTS: // METHODS
Q_SIGNALS: // SIGNALS
    void PropertiesChanged();
};

#endif
