/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./networkmanager-qt/src/dbus/introspection/org.freedesktop.NetworkManager.IP4Config.xml -a ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.IP4ConfigAdaptor -i ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.IP4Config.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.IP4ConfigAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class IP4ConfigAdaptor
 */

IP4ConfigAdaptor::IP4ConfigAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

IP4ConfigAdaptor::~IP4ConfigAdaptor()
{
    // destructor
}

NMVariantMapList IP4ConfigAdaptor::addressData() const
{
    // get the value of property AddressData
    return qvariant_cast< NMVariantMapList >(parent()->property("AddressData"));
}

UIntListList IP4ConfigAdaptor::addresses() const
{
    // get the value of property Addresses
    return qvariant_cast< UIntListList >(parent()->property("Addresses"));
}

QStringList IP4ConfigAdaptor::dnsOptions() const
{
    // get the value of property DnsOptions
    return qvariant_cast< QStringList >(parent()->property("DnsOptions"));
}

int IP4ConfigAdaptor::dnsPriority() const
{
    // get the value of property DnsPriority
    return qvariant_cast< int >(parent()->property("DnsPriority"));
}

QStringList IP4ConfigAdaptor::domains() const
{
    // get the value of property Domains
    return qvariant_cast< QStringList >(parent()->property("Domains"));
}

QString IP4ConfigAdaptor::gateway() const
{
    // get the value of property Gateway
    return qvariant_cast< QString >(parent()->property("Gateway"));
}

UIntList IP4ConfigAdaptor::nameservers() const
{
    // get the value of property Nameservers
    return qvariant_cast< UIntList >(parent()->property("Nameservers"));
}

NMVariantMapList IP4ConfigAdaptor::routeData() const
{
    // get the value of property RouteData
    return qvariant_cast< NMVariantMapList >(parent()->property("RouteData"));
}

UIntListList IP4ConfigAdaptor::routes() const
{
    // get the value of property Routes
    return qvariant_cast< UIntListList >(parent()->property("Routes"));
}

QStringList IP4ConfigAdaptor::searches() const
{
    // get the value of property Searches
    return qvariant_cast< QStringList >(parent()->property("Searches"));
}

UIntList IP4ConfigAdaptor::winsServers() const
{
    // get the value of property WinsServers
    return qvariant_cast< UIntList >(parent()->property("WinsServers"));
}

