/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./networkmanager-qt/src/dbus/introspection/org.freedesktop.NetworkManager.PPP.xml -a ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.PPPAdaptor -i ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.PPP.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.PPPAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class PPPAdaptor
 */

PPPAdaptor::PPPAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

PPPAdaptor::~PPPAdaptor()
{
    // destructor
}

QString PPPAdaptor::NeedSecrets(QString &password)
{
    // handle method call org.freedesktop.NetworkManager.PPP.NeedSecrets
    //return static_cast<YourObjectType *>(parent())->NeedSecrets(password);
}

void PPPAdaptor::SetIp4Config(const QVariantMap &config)
{
    // handle method call org.freedesktop.NetworkManager.PPP.SetIp4Config
    QMetaObject::invokeMethod(parent(), "SetIp4Config", Q_ARG(QVariantMap, config));
}

void PPPAdaptor::SetIp6Config(const QVariantMap &config)
{
    // handle method call org.freedesktop.NetworkManager.PPP.SetIp6Config
    QMetaObject::invokeMethod(parent(), "SetIp6Config", Q_ARG(QVariantMap, config));
}

void PPPAdaptor::SetState(uint state)
{
    // handle method call org.freedesktop.NetworkManager.PPP.SetState
    QMetaObject::invokeMethod(parent(), "SetState", Q_ARG(uint, state));
}

