/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./networkmanager-qt/src/dbus/introspection/org.freedesktop.NetworkManager.Device.Vxlan.xml -a ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.VxlanAdaptor -i ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.Vxlan.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.VxlanAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class VxlanAdaptor
 */

VxlanAdaptor::VxlanAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

VxlanAdaptor::~VxlanAdaptor()
{
    // destructor
}

uint VxlanAdaptor::ageing() const
{
    // get the value of property Ageing
    return qvariant_cast< uint >(parent()->property("Ageing"));
}

ushort VxlanAdaptor::dstPort() const
{
    // get the value of property DstPort
    return qvariant_cast< ushort >(parent()->property("DstPort"));
}

QString VxlanAdaptor::group() const
{
    // get the value of property Group
    return qvariant_cast< QString >(parent()->property("Group"));
}

QString VxlanAdaptor::hwAddress() const
{
    // get the value of property HwAddress
    return qvariant_cast< QString >(parent()->property("HwAddress"));
}

uint VxlanAdaptor::id() const
{
    // get the value of property Id
    return qvariant_cast< uint >(parent()->property("Id"));
}

bool VxlanAdaptor::l2miss() const
{
    // get the value of property L2miss
    return qvariant_cast< bool >(parent()->property("L2miss"));
}

bool VxlanAdaptor::l3miss() const
{
    // get the value of property L3miss
    return qvariant_cast< bool >(parent()->property("L3miss"));
}

bool VxlanAdaptor::learning() const
{
    // get the value of property Learning
    return qvariant_cast< bool >(parent()->property("Learning"));
}

uint VxlanAdaptor::limit() const
{
    // get the value of property Limit
    return qvariant_cast< uint >(parent()->property("Limit"));
}

QString VxlanAdaptor::local() const
{
    // get the value of property Local
    return qvariant_cast< QString >(parent()->property("Local"));
}

QDBusObjectPath VxlanAdaptor::parent() const
{
    // get the value of property Parent
    return qvariant_cast< QDBusObjectPath >(parent()->property("Parent"));
}

bool VxlanAdaptor::proxy() const
{
    // get the value of property Proxy
    return qvariant_cast< bool >(parent()->property("Proxy"));
}

bool VxlanAdaptor::rsc() const
{
    // get the value of property Rsc
    return qvariant_cast< bool >(parent()->property("Rsc"));
}

ushort VxlanAdaptor::srcPortMax() const
{
    // get the value of property SrcPortMax
    return qvariant_cast< ushort >(parent()->property("SrcPortMax"));
}

ushort VxlanAdaptor::srcPortMin() const
{
    // get the value of property SrcPortMin
    return qvariant_cast< ushort >(parent()->property("SrcPortMin"));
}

uchar VxlanAdaptor::tos() const
{
    // get the value of property Tos
    return qvariant_cast< uchar >(parent()->property("Tos"));
}

uchar VxlanAdaptor::ttl() const
{
    // get the value of property Ttl
    return qvariant_cast< uchar >(parent()->property("Ttl"));
}

