/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./networkmanager-qt/src/dbus/introspection/org.freedesktop.NetworkManager.Device.Team.xml -a ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.TeamAdaptor -i ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.Team.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.TeamAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class TeamAdaptor
 */

TeamAdaptor::TeamAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

TeamAdaptor::~TeamAdaptor()
{
    // destructor
}

bool TeamAdaptor::carrier() const
{
    // get the value of property Carrier
    return qvariant_cast< bool >(parent()->property("Carrier"));
}

QString TeamAdaptor::config() const
{
    // get the value of property Config
    return qvariant_cast< QString >(parent()->property("Config"));
}

QString TeamAdaptor::hwAddress() const
{
    // get the value of property HwAddress
    return qvariant_cast< QString >(parent()->property("HwAddress"));
}

QList<QDBusObjectPath> TeamAdaptor::slaves() const
{
    // get the value of property Slaves
    return qvariant_cast< QList<QDBusObjectPath> >(parent()->property("Slaves"));
}

