/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./networkmanager-qt/src/dbus/introspection/org.freedesktop.NetworkManager.Device.IPTunnel.xml -a ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.IPTunnelAdaptor -i ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.IPTunnel.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ORG_FREEDESKTOP_NETWORKMANAGER_DEVICE_IPTUNNELADAPTOR_H
#define ORG_FREEDESKTOP_NETWORKMANAGER_DEVICE_IPTUNNELADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.IPTunnel.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.freedesktop.NetworkManager.Device.IPTunnel
 */
class IPTunnelAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.freedesktop.NetworkManager.Device.IPTunnel")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.freedesktop.NetworkManager.Device.IPTunnel\">\n"
"    <property access=\"read\" type=\"u\" name=\"Mode\"/>\n"
"    <property access=\"read\" type=\"o\" name=\"Parent\"/>\n"
"    <property access=\"read\" type=\"s\" name=\"Local\"/>\n"
"    <property access=\"read\" type=\"s\" name=\"Remote\"/>\n"
"    <property access=\"read\" type=\"y\" name=\"Ttl\"/>\n"
"    <property access=\"read\" type=\"y\" name=\"Tos\"/>\n"
"    <property access=\"read\" type=\"b\" name=\"PathMtuDiscovery\"/>\n"
"    <property access=\"read\" type=\"s\" name=\"InputKey\"/>\n"
"    <property access=\"read\" type=\"s\" name=\"OutputKey\"/>\n"
"    <property access=\"read\" type=\"y\" name=\"EncapsulationLimit\"/>\n"
"    <property access=\"read\" type=\"u\" name=\"FlowLabel\"/>\n"
"    <signal name=\"PropertiesChanged\">\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    IPTunnelAdaptor(QObject *parent);
    virtual ~IPTunnelAdaptor();

public: // PROPERTIES
    Q_PROPERTY(uchar EncapsulationLimit READ encapsulationLimit)
    uchar encapsulationLimit() const;

    Q_PROPERTY(uint FlowLabel READ flowLabel)
    uint flowLabel() const;

    Q_PROPERTY(QString InputKey READ inputKey)
    QString inputKey() const;

    Q_PROPERTY(QString Local READ local)
    QString local() const;

    Q_PROPERTY(uint Mode READ mode)
    uint mode() const;

    Q_PROPERTY(QString OutputKey READ outputKey)
    QString outputKey() const;

    Q_PROPERTY(QDBusObjectPath Parent READ parent)
    QDBusObjectPath parent() const;

    Q_PROPERTY(bool PathMtuDiscovery READ pathMtuDiscovery)
    bool pathMtuDiscovery() const;

    Q_PROPERTY(QString Remote READ remote)
    QString remote() const;

    Q_PROPERTY(uchar Tos READ tos)
    uchar tos() const;

    Q_PROPERTY(uchar Ttl READ ttl)
    uchar ttl() const;

public Q_SLOTS: // METHODS
Q_SIGNALS: // SIGNALS
    void PropertiesChanged();
};

#endif
