/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./networkmanager-qt/src/dbus/introspection/org.freedesktop.NetworkManager.VPN.Plugin.xml -a ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.VPN.PluginAdaptor -i ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.VPN.Plugin.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ORG_FREEDESKTOP_NETWORKMANAGER_VPN_PLUGINADAPTOR_H
#define ORG_FREEDESKTOP_NETWORKMANAGER_VPN_PLUGINADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.VPN.Plugin.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.freedesktop.NetworkManager.VPN.Plugin
 */
class PluginAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.freedesktop.NetworkManager.VPN.Plugin")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.freedesktop.NetworkManager.VPN.Plugin\">\n"
"    <annotation value=\"VpnPlugin\" name=\"org.gtk.GDBus.C.Name\"/>\n"
"    <method name=\"Connect\">\n"
"      <annotation value=\"impl_vpn_plugin_connect\" name=\"org.freedesktop.DBus.GLib.CSymbol\"/>\n"
"      <annotation value=\"NMVariantMapMap\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"      <arg direction=\"in\" type=\"a{sa{sv}}\" name=\"connection\"/>\n"
"    </method>\n"
"    <method name=\"ConnectInteractive\">\n"
"      <annotation value=\"impl_vpn_plugin_connect_interactive\" name=\"org.freedesktop.DBus.GLib.CSymbol\"/>\n"
"      <annotation value=\"NMVariantMapMap\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"      <arg direction=\"in\" type=\"a{sa{sv}}\" name=\"connection\"/>\n"
"      <annotation value=\"NMVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.In1\"/>\n"
"      <arg direction=\"in\" type=\"a{sv}\" name=\"details\"/>\n"
"    </method>\n"
"    <method name=\"NeedSecrets\">\n"
"      <annotation value=\"impl_vpn_plugin_need_secrets\" name=\"org.freedesktop.DBus.GLib.CSymbol\"/>\n"
"      <annotation value=\"NMVariantMapMap\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"      <arg direction=\"in\" type=\"a{sa{sv}}\" name=\"settings\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"setting_name\"/>\n"
"    </method>\n"
"    <method name=\"Disconnect\">\n"
"      <annotation value=\"impl_vpn_plugin_disconnect\" name=\"org.freedesktop.DBus.GLib.CSymbol\"/>\n"
"    </method>\n"
"    <method name=\"SetConfig\">\n"
"      <annotation value=\"impl_vpn_plugin_set_config\" name=\"org.freedesktop.DBus.GLib.CSymbol\"/>\n"
"      <annotation value=\"NMVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"      <arg direction=\"in\" type=\"a{sv}\" name=\"config\"/>\n"
"    </method>\n"
"    <method name=\"SetIp4Config\">\n"
"      <annotation value=\"impl_vpn_plugin_set_ip4_config\" name=\"org.freedesktop.DBus.GLib.CSymbol\"/>\n"
"      <annotation value=\"NMVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"      <arg direction=\"in\" type=\"a{sv}\" name=\"config\"/>\n"
"    </method>\n"
"    <method name=\"SetIp6Config\">\n"
"      <annotation value=\"impl_vpn_plugin_set_ip6_config\" name=\"org.freedesktop.DBus.GLib.CSymbol\"/>\n"
"      <annotation value=\"NMVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"      <arg direction=\"in\" type=\"a{sv}\" name=\"config\"/>\n"
"    </method>\n"
"    <method name=\"SetFailure\">\n"
"      <annotation value=\"impl_vpn_plugin_set_failure\" name=\"org.freedesktop.DBus.GLib.CSymbol\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"reason\"/>\n"
"    </method>\n"
"    <property access=\"read\" type=\"u\" name=\"State\"/>\n"
"    <signal name=\"StateChanged\">\n"
"      <arg type=\"u\" name=\"state\"/>\n"
"    </signal>\n"
"    <signal name=\"SecretsRequired\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"message\"/>\n"
"      <arg direction=\"out\" type=\"as\" name=\"secrets\"/>\n"
"    </signal>\n"
"    <method name=\"NewSecrets\">\n"
"      <annotation value=\"impl_vpn_plugin_new_secrets\" name=\"org.freedesktop.DBus.GLib.CSymbol\"/>\n"
"      <annotation value=\"NMVariantMapMap\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"      <arg direction=\"in\" type=\"a{sa{sv}}\" name=\"connection\"/>\n"
"    </method>\n"
"    <signal name=\"Config\">\n"
"      <annotation value=\"NMVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"      <arg type=\"a{sv}\" name=\"config\"/>\n"
"    </signal>\n"
"    <signal name=\"Ip4Config\">\n"
"      <annotation value=\"NMVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"      <arg type=\"a{sv}\" name=\"ip4config\"/>\n"
"    </signal>\n"
"    <signal name=\"Ip6Config\">\n"
"      <annotation value=\"NMVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"      <arg type=\"a{sv}\" name=\"ip6config\"/>\n"
"    </signal>\n"
"    <signal name=\"LoginBanner\">\n"
"      <arg type=\"s\" name=\"banner\"/>\n"
"    </signal>\n"
"    <signal name=\"Failure\">\n"
"      <arg type=\"u\" name=\"reason\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    PluginAdaptor(QObject *parent);
    virtual ~PluginAdaptor();

public: // PROPERTIES
    Q_PROPERTY(uint State READ state)
    uint state() const;

public Q_SLOTS: // METHODS
    void Connect(NMVariantMapMap connection);
    void ConnectInteractive(NMVariantMapMap connection, NMVariantMap details);
    void Disconnect();
    QString NeedSecrets(NMVariantMapMap settings);
    void NewSecrets(NMVariantMapMap connection);
    void SetConfig(NMVariantMap config);
    void SetFailure(const QString &reason);
    void SetIp4Config(NMVariantMap config);
    void SetIp6Config(NMVariantMap config);
Q_SIGNALS: // SIGNALS
    void Config(NMVariantMap config);
    void Failure(uint reason);
    void Ip4Config(NMVariantMap ip4config);
    void Ip6Config(NMVariantMap ip6config);
    void LoginBanner(const QString &banner);
    void SecretsRequired(const QString &message, const QStringList &secrets);
    void StateChanged(uint state);
};

#endif
