/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./networkmanager-qt/src/dbus/introspection/org.freedesktop.NetworkManager.Device.Gre.xml -a ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.GreAdaptor -i ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.Gre.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ORG_FREEDESKTOP_NETWORKMANAGER_DEVICE_GREADAPTOR_H
#define ORG_FREEDESKTOP_NETWORKMANAGER_DEVICE_GREADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.Gre.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.freedesktop.NetworkManager.Device.Gre
 */
class GreAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.freedesktop.NetworkManager.Device.Gre")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.freedesktop.NetworkManager.Device.Gre\">\n"
"    <property access=\"read\" type=\"o\" name=\"Parent\">\n"
"    </property>\n"
"    <property access=\"read\" type=\"q\" name=\"InputFlags\">\n"
"    </property>\n"
"    <property access=\"read\" type=\"q\" name=\"OutputFlags\">\n"
"    </property>\n"
"    <property access=\"read\" type=\"u\" name=\"InputKey\">\n"
"    </property>\n"
"    <property access=\"read\" type=\"u\" name=\"OutputKey\">\n"
"    </property>\n"
"    <property access=\"read\" type=\"s\" name=\"Local\">\n"
"    </property>\n"
"    <property access=\"read\" type=\"s\" name=\"Remote\">\n"
"    </property>\n"
"    <property access=\"read\" type=\"y\" name=\"Ttl\">\n"
"    </property>\n"
"    <property access=\"read\" type=\"y\" name=\"Tos\">\n"
"    </property>\n"
"    <property access=\"read\" type=\"b\" name=\"PathMtuDiscovery\">\n"
"    </property>\n"
"    <signal name=\"PropertiesChanged\">\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    GreAdaptor(QObject *parent);
    virtual ~GreAdaptor();

public: // PROPERTIES
    Q_PROPERTY(ushort InputFlags READ inputFlags)
    ushort inputFlags() const;

    Q_PROPERTY(uint InputKey READ inputKey)
    uint inputKey() const;

    Q_PROPERTY(QString Local READ local)
    QString local() const;

    Q_PROPERTY(ushort OutputFlags READ outputFlags)
    ushort outputFlags() const;

    Q_PROPERTY(uint OutputKey READ outputKey)
    uint outputKey() const;

    Q_PROPERTY(QDBusObjectPath Parent READ parent)
    QDBusObjectPath parent() const;

    Q_PROPERTY(bool PathMtuDiscovery READ pathMtuDiscovery)
    bool pathMtuDiscovery() const;

    Q_PROPERTY(QString Remote READ remote)
    QString remote() const;

    Q_PROPERTY(uchar Tos READ tos)
    uchar tos() const;

    Q_PROPERTY(uchar Ttl READ ttl)
    uchar ttl() const;

public Q_SLOTS: // METHODS
Q_SIGNALS: // SIGNALS
    void PropertiesChanged();
};

#endif
