/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./networkmanager-qt/src/dbus/introspection/org.freedesktop.NetworkManager.AccessPoint.xml -a ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.AccessPointAdaptor -i ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.AccessPoint.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ORG_FREEDESKTOP_NETWORKMANAGER_ACCESSPOINTADAPTOR_H
#define ORG_FREEDESKTOP_NETWORKMANAGER_ACCESSPOINTADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.AccessPoint.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.freedesktop.NetworkManager.AccessPoint
 */
class AccessPointAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.freedesktop.NetworkManager.AccessPoint")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.freedesktop.NetworkManager.AccessPoint\">\n"
"    <property access=\"read\" type=\"u\" name=\"Flags\"/>\n"
"    <property access=\"read\" type=\"u\" name=\"WpaFlags\"/>\n"
"    <property access=\"read\" type=\"u\" name=\"RsnFlags\"/>\n"
"    <property access=\"read\" type=\"ay\" name=\"Ssid\">\n"
"      <annotation value=\"1\" name=\"org.gtk.GDBus.C.ForceGVariant\"/>\n"
"    </property>\n"
"    <property access=\"read\" type=\"u\" name=\"Frequency\"/>\n"
"    <property access=\"read\" type=\"s\" name=\"HwAddress\"/>\n"
"    <property access=\"read\" type=\"u\" name=\"Mode\"/>\n"
"    <property access=\"read\" type=\"u\" name=\"MaxBitrate\"/>\n"
"    <property access=\"read\" type=\"y\" name=\"Strength\"/>\n"
"    <property access=\"read\" type=\"i\" name=\"LastSeen\"/>\n"
"    <signal name=\"PropertiesChanged\">\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    AccessPointAdaptor(QObject *parent);
    virtual ~AccessPointAdaptor();

public: // PROPERTIES
    Q_PROPERTY(uint Flags READ flags)
    uint flags() const;

    Q_PROPERTY(uint Frequency READ frequency)
    uint frequency() const;

    Q_PROPERTY(QString HwAddress READ hwAddress)
    QString hwAddress() const;

    Q_PROPERTY(int LastSeen READ lastSeen)
    int lastSeen() const;

    Q_PROPERTY(uint MaxBitrate READ maxBitrate)
    uint maxBitrate() const;

    Q_PROPERTY(uint Mode READ mode)
    uint mode() const;

    Q_PROPERTY(uint RsnFlags READ rsnFlags)
    uint rsnFlags() const;

    Q_PROPERTY(QByteArray Ssid READ ssid)
    QByteArray ssid() const;

    Q_PROPERTY(uchar Strength READ strength)
    uchar strength() const;

    Q_PROPERTY(uint WpaFlags READ wpaFlags)
    uint wpaFlags() const;

public Q_SLOTS: // METHODS
Q_SIGNALS: // SIGNALS
    void PropertiesChanged();
};

#endif
