/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./networkmanager-qt/src/dbus/introspection/org.freedesktop.NetworkManager.Device.Vxlan.xml -a ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.VxlanAdaptor -i ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.Vxlan.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ORG_FREEDESKTOP_NETWORKMANAGER_DEVICE_VXLANADAPTOR_H
#define ORG_FREEDESKTOP_NETWORKMANAGER_DEVICE_VXLANADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.Vxlan.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.freedesktop.NetworkManager.Device.Vxlan
 */
class VxlanAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.freedesktop.NetworkManager.Device.Vxlan")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.freedesktop.NetworkManager.Device.Vxlan\">\n"
"    <property access=\"read\" type=\"o\" name=\"Parent\"/>\n"
"    <property access=\"read\" type=\"s\" name=\"HwAddress\"/>\n"
"    <property access=\"read\" type=\"u\" name=\"Id\"/>\n"
"    <property access=\"read\" type=\"s\" name=\"Group\"/>\n"
"    <property access=\"read\" type=\"s\" name=\"Local\"/>\n"
"    <property access=\"read\" type=\"y\" name=\"Tos\"/>\n"
"    <property access=\"read\" type=\"y\" name=\"Ttl\"/>\n"
"    <property access=\"read\" type=\"b\" name=\"Learning\"/>\n"
"    <property access=\"read\" type=\"u\" name=\"Ageing\"/>\n"
"    <property access=\"read\" type=\"u\" name=\"Limit\"/>\n"
"    <property access=\"read\" type=\"q\" name=\"DstPort\"/>\n"
"    <property access=\"read\" type=\"q\" name=\"SrcPortMin\"/>\n"
"    <property access=\"read\" type=\"q\" name=\"SrcPortMax\"/>\n"
"    <property access=\"read\" type=\"b\" name=\"Proxy\"/>\n"
"    <property access=\"read\" type=\"b\" name=\"Rsc\"/>\n"
"    <property access=\"read\" type=\"b\" name=\"L2miss\"/>\n"
"    <property access=\"read\" type=\"b\" name=\"L3miss\"/>\n"
"    <signal name=\"PropertiesChanged\">\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    VxlanAdaptor(QObject *parent);
    virtual ~VxlanAdaptor();

public: // PROPERTIES
    Q_PROPERTY(uint Ageing READ ageing)
    uint ageing() const;

    Q_PROPERTY(ushort DstPort READ dstPort)
    ushort dstPort() const;

    Q_PROPERTY(QString Group READ group)
    QString group() const;

    Q_PROPERTY(QString HwAddress READ hwAddress)
    QString hwAddress() const;

    Q_PROPERTY(uint Id READ id)
    uint id() const;

    Q_PROPERTY(bool L2miss READ l2miss)
    bool l2miss() const;

    Q_PROPERTY(bool L3miss READ l3miss)
    bool l3miss() const;

    Q_PROPERTY(bool Learning READ learning)
    bool learning() const;

    Q_PROPERTY(uint Limit READ limit)
    uint limit() const;

    Q_PROPERTY(QString Local READ local)
    QString local() const;

    Q_PROPERTY(QDBusObjectPath Parent READ parent)
    QDBusObjectPath parent() const;

    Q_PROPERTY(bool Proxy READ proxy)
    bool proxy() const;

    Q_PROPERTY(bool Rsc READ rsc)
    bool rsc() const;

    Q_PROPERTY(ushort SrcPortMax READ srcPortMax)
    ushort srcPortMax() const;

    Q_PROPERTY(ushort SrcPortMin READ srcPortMin)
    ushort srcPortMin() const;

    Q_PROPERTY(uchar Tos READ tos)
    uchar tos() const;

    Q_PROPERTY(uchar Ttl READ ttl)
    uchar ttl() const;

public Q_SLOTS: // METHODS
Q_SIGNALS: // SIGNALS
    void PropertiesChanged();
};

#endif
