/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./networkmanager-qt/src/dbus/introspection/org.freedesktop.NetworkManager.Device.Macsec.xml -a ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.MacsecAdaptor -i ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.Macsec.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.MacsecAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class MacsecAdaptor
 */

MacsecAdaptor::MacsecAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

MacsecAdaptor::~MacsecAdaptor()
{
    // destructor
}

qulonglong MacsecAdaptor::cipherSuite() const
{
    // get the value of property CipherSuite
    return qvariant_cast< qulonglong >(parent()->property("CipherSuite"));
}

uchar MacsecAdaptor::encodingSa() const
{
    // get the value of property EncodingSa
    return qvariant_cast< uchar >(parent()->property("EncodingSa"));
}

bool MacsecAdaptor::encrypt() const
{
    // get the value of property Encrypt
    return qvariant_cast< bool >(parent()->property("Encrypt"));
}

bool MacsecAdaptor::es() const
{
    // get the value of property Es
    return qvariant_cast< bool >(parent()->property("Es"));
}

uchar MacsecAdaptor::icvLength() const
{
    // get the value of property IcvLength
    return qvariant_cast< uchar >(parent()->property("IcvLength"));
}

bool MacsecAdaptor::includeSci() const
{
    // get the value of property IncludeSci
    return qvariant_cast< bool >(parent()->property("IncludeSci"));
}

QDBusObjectPath MacsecAdaptor::parent() const
{
    // get the value of property Parent
    return qvariant_cast< QDBusObjectPath >(parent()->property("Parent"));
}

bool MacsecAdaptor::protect() const
{
    // get the value of property Protect
    return qvariant_cast< bool >(parent()->property("Protect"));
}

bool MacsecAdaptor::replayProtect() const
{
    // get the value of property ReplayProtect
    return qvariant_cast< bool >(parent()->property("ReplayProtect"));
}

bool MacsecAdaptor::scb() const
{
    // get the value of property Scb
    return qvariant_cast< bool >(parent()->property("Scb"));
}

qulonglong MacsecAdaptor::sci() const
{
    // get the value of property Sci
    return qvariant_cast< qulonglong >(parent()->property("Sci"));
}

QString MacsecAdaptor::validation() const
{
    // get the value of property Validation
    return qvariant_cast< QString >(parent()->property("Validation"));
}

uint MacsecAdaptor::window() const
{
    // get the value of property Window
    return qvariant_cast< uint >(parent()->property("Window"));
}

