/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./networkmanager-qt/src/dbus/introspection/org.freedesktop.NetworkManager.Device.Wireless.xml -a ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.WirelessAdaptor -i ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.Wireless.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.WirelessAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class WirelessAdaptor
 */

WirelessAdaptor::WirelessAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

WirelessAdaptor::~WirelessAdaptor()
{
    // destructor
}

QList<QDBusObjectPath> WirelessAdaptor::accessPoints() const
{
    // get the value of property AccessPoints
    return qvariant_cast< QList<QDBusObjectPath> >(parent()->property("AccessPoints"));
}

QDBusObjectPath WirelessAdaptor::activeAccessPoint() const
{
    // get the value of property ActiveAccessPoint
    return qvariant_cast< QDBusObjectPath >(parent()->property("ActiveAccessPoint"));
}

uint WirelessAdaptor::bitrate() const
{
    // get the value of property Bitrate
    return qvariant_cast< uint >(parent()->property("Bitrate"));
}

QString WirelessAdaptor::hwAddress() const
{
    // get the value of property HwAddress
    return qvariant_cast< QString >(parent()->property("HwAddress"));
}

uint WirelessAdaptor::mode() const
{
    // get the value of property Mode
    return qvariant_cast< uint >(parent()->property("Mode"));
}

QString WirelessAdaptor::permHwAddress() const
{
    // get the value of property PermHwAddress
    return qvariant_cast< QString >(parent()->property("PermHwAddress"));
}

uint WirelessAdaptor::wirelessCapabilities() const
{
    // get the value of property WirelessCapabilities
    return qvariant_cast< uint >(parent()->property("WirelessCapabilities"));
}

QList<QDBusObjectPath> WirelessAdaptor::GetAccessPoints()
{
    // handle method call org.freedesktop.NetworkManager.Device.Wireless.GetAccessPoints
    QList<QDBusObjectPath> access_points;
    QMetaObject::invokeMethod(parent(), "GetAccessPoints", Q_RETURN_ARG(QList<QDBusObjectPath>, access_points));
    return access_points;
}

QList<QDBusObjectPath> WirelessAdaptor::GetAllAccessPoints()
{
    // handle method call org.freedesktop.NetworkManager.Device.Wireless.GetAllAccessPoints
    QList<QDBusObjectPath> access_points;
    QMetaObject::invokeMethod(parent(), "GetAllAccessPoints", Q_RETURN_ARG(QList<QDBusObjectPath>, access_points));
    return access_points;
}

void WirelessAdaptor::RequestScan(const QVariantMap &options)
{
    // handle method call org.freedesktop.NetworkManager.Device.Wireless.RequestScan
    QMetaObject::invokeMethod(parent(), "RequestScan", Q_ARG(QVariantMap, options));
}

