/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./networkmanager-qt/src/dbus/introspection/org.freedesktop.NetworkManager.Checkpoint.xml -a ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.CheckpointAdaptor -i ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Checkpoint.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.CheckpointAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class CheckpointAdaptor
 */

CheckpointAdaptor::CheckpointAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

CheckpointAdaptor::~CheckpointAdaptor()
{
    // destructor
}

qlonglong CheckpointAdaptor::created() const
{
    // get the value of property Created
    return qvariant_cast< qlonglong >(parent()->property("Created"));
}

QList<QDBusObjectPath> CheckpointAdaptor::devices() const
{
    // get the value of property Devices
    return qvariant_cast< QList<QDBusObjectPath> >(parent()->property("Devices"));
}

uint CheckpointAdaptor::rollbackTimeout() const
{
    // get the value of property RollbackTimeout
    return qvariant_cast< uint >(parent()->property("RollbackTimeout"));
}

