/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./networkmanager-qt/src/dbus/introspection/org.freedesktop.NetworkManager.Device.Statistics.xml -a ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.StatisticsAdaptor -i ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.Statistics.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.StatisticsAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class StatisticsAdaptor
 */

StatisticsAdaptor::StatisticsAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

StatisticsAdaptor::~StatisticsAdaptor()
{
    // destructor
}

uint StatisticsAdaptor::refreshRateMs() const
{
    // get the value of property RefreshRateMs
    return qvariant_cast< uint >(parent()->property("RefreshRateMs"));
}

void StatisticsAdaptor::setRefreshRateMs(uint value)
{
    // set the value of property RefreshRateMs
    parent()->setProperty("RefreshRateMs", QVariant::fromValue(value));
}

qulonglong StatisticsAdaptor::rxBytes() const
{
    // get the value of property RxBytes
    return qvariant_cast< qulonglong >(parent()->property("RxBytes"));
}

qulonglong StatisticsAdaptor::txBytes() const
{
    // get the value of property TxBytes
    return qvariant_cast< qulonglong >(parent()->property("TxBytes"));
}

