/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./networkmanager-qt/src/dbus/introspection/org.freedesktop.NetworkManager.Device.Macsec.xml -a ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.MacsecAdaptor -i ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.Macsec.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ORG_FREEDESKTOP_NETWORKMANAGER_DEVICE_MACSECADAPTOR_H
#define ORG_FREEDESKTOP_NETWORKMANAGER_DEVICE_MACSECADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.Macsec.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.freedesktop.NetworkManager.Device.Macsec
 */
class MacsecAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.freedesktop.NetworkManager.Device.Macsec")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.freedesktop.NetworkManager.Device.Macsec\">\n"
"    <property access=\"read\" type=\"o\" name=\"Parent\"/>\n"
"    <property access=\"read\" type=\"t\" name=\"Sci\"/>\n"
"    <property access=\"read\" type=\"y\" name=\"IcvLength\"/>\n"
"    <property access=\"read\" type=\"t\" name=\"CipherSuite\"/>\n"
"    <property access=\"read\" type=\"u\" name=\"Window\"/>\n"
"    <property access=\"read\" type=\"y\" name=\"EncodingSa\"/>\n"
"    <property access=\"read\" type=\"s\" name=\"Validation\"/>\n"
"    <property access=\"read\" type=\"b\" name=\"Encrypt\"/>\n"
"    <property access=\"read\" type=\"b\" name=\"Protect\"/>\n"
"    <property access=\"read\" type=\"b\" name=\"IncludeSci\"/>\n"
"    <property access=\"read\" type=\"b\" name=\"Es\"/>\n"
"    <property access=\"read\" type=\"b\" name=\"Scb\"/>\n"
"    <property access=\"read\" type=\"b\" name=\"ReplayProtect\"/>\n"
"    <signal name=\"PropertiesChanged\">\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    MacsecAdaptor(QObject *parent);
    virtual ~MacsecAdaptor();

public: // PROPERTIES
    Q_PROPERTY(qulonglong CipherSuite READ cipherSuite)
    qulonglong cipherSuite() const;

    Q_PROPERTY(uchar EncodingSa READ encodingSa)
    uchar encodingSa() const;

    Q_PROPERTY(bool Encrypt READ encrypt)
    bool encrypt() const;

    Q_PROPERTY(bool Es READ es)
    bool es() const;

    Q_PROPERTY(uchar IcvLength READ icvLength)
    uchar icvLength() const;

    Q_PROPERTY(bool IncludeSci READ includeSci)
    bool includeSci() const;

    Q_PROPERTY(QDBusObjectPath Parent READ parent)
    QDBusObjectPath parent() const;

    Q_PROPERTY(bool Protect READ protect)
    bool protect() const;

    Q_PROPERTY(bool ReplayProtect READ replayProtect)
    bool replayProtect() const;

    Q_PROPERTY(bool Scb READ scb)
    bool scb() const;

    Q_PROPERTY(qulonglong Sci READ sci)
    qulonglong sci() const;

    Q_PROPERTY(QString Validation READ validation)
    QString validation() const;

    Q_PROPERTY(uint Window READ window)
    uint window() const;

public Q_SLOTS: // METHODS
Q_SIGNALS: // SIGNALS
    void PropertiesChanged();
};

#endif
