/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./networkmanager-qt/src/dbus/introspection/org.freedesktop.NetworkManager.Device.OlpcMesh.xml -a ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.OlpcMeshAdaptor -i ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.OlpcMesh.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.OlpcMeshAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class OlpcMeshAdaptor
 */

OlpcMeshAdaptor::OlpcMeshAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

OlpcMeshAdaptor::~OlpcMeshAdaptor()
{
    // destructor
}

uint OlpcMeshAdaptor::activeChannel() const
{
    // get the value of property ActiveChannel
    return qvariant_cast< uint >(parent()->property("ActiveChannel"));
}

QDBusObjectPath OlpcMeshAdaptor::companion() const
{
    // get the value of property Companion
    return qvariant_cast< QDBusObjectPath >(parent()->property("Companion"));
}

QString OlpcMeshAdaptor::hwAddress() const
{
    // get the value of property HwAddress
    return qvariant_cast< QString >(parent()->property("HwAddress"));
}

