/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./networkmanager-qt/src/dbus/introspection/org.freedesktop.NetworkManager.Device.Vlan.xml -a ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.VlanAdaptor -i ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.Vlan.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.VlanAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class VlanAdaptor
 */

VlanAdaptor::VlanAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

VlanAdaptor::~VlanAdaptor()
{
    // destructor
}

bool VlanAdaptor::carrier() const
{
    // get the value of property Carrier
    return qvariant_cast< bool >(parent()->property("Carrier"));
}

QString VlanAdaptor::hwAddress() const
{
    // get the value of property HwAddress
    return qvariant_cast< QString >(parent()->property("HwAddress"));
}

QDBusObjectPath VlanAdaptor::parent() const
{
    // get the value of property Parent
    return qvariant_cast< QDBusObjectPath >(parent()->property("Parent"));
}

uint VlanAdaptor::vlanId() const
{
    // get the value of property VlanId
    return qvariant_cast< uint >(parent()->property("VlanId"));
}

