/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./networkmanager-qt/src/dbus/introspection/org.freedesktop.NetworkManager.Device.Wired.xml -a ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.WiredAdaptor -i ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.Wired.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.WiredAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class WiredAdaptor
 */

WiredAdaptor::WiredAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

WiredAdaptor::~WiredAdaptor()
{
    // destructor
}

bool WiredAdaptor::carrier() const
{
    // get the value of property Carrier
    return qvariant_cast< bool >(parent()->property("Carrier"));
}

QString WiredAdaptor::hwAddress() const
{
    // get the value of property HwAddress
    return qvariant_cast< QString >(parent()->property("HwAddress"));
}

QString WiredAdaptor::permHwAddress() const
{
    // get the value of property PermHwAddress
    return qvariant_cast< QString >(parent()->property("PermHwAddress"));
}

QStringList WiredAdaptor::s390Subchannels() const
{
    // get the value of property S390Subchannels
    return qvariant_cast< QStringList >(parent()->property("S390Subchannels"));
}

uint WiredAdaptor::speed() const
{
    // get the value of property Speed
    return qvariant_cast< uint >(parent()->property("Speed"));
}

