/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./networkmanager-qt/src/dbus/introspection/org.freedesktop.NetworkManager.Device.Modem.xml -a ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.ModemAdaptor -i ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.Modem.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ORG_FREEDESKTOP_NETWORKMANAGER_DEVICE_MODEMADAPTOR_H
#define ORG_FREEDESKTOP_NETWORKMANAGER_DEVICE_MODEMADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.Modem.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.freedesktop.NetworkManager.Device.Modem
 */
class ModemAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.freedesktop.NetworkManager.Device.Modem")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.freedesktop.NetworkManager.Device.Modem\">\n"
"    <signal name=\"PropertiesChanged\">\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"    </signal>\n"
"    <property access=\"read\" type=\"u\" name=\"ModemCapabilities\"/>\n"
"    <property access=\"read\" type=\"u\" name=\"CurrentCapabilities\"/>\n"
"  </interface>\n"
        "")
public:
    ModemAdaptor(QObject *parent);
    virtual ~ModemAdaptor();

public: // PROPERTIES
    Q_PROPERTY(uint CurrentCapabilities READ currentCapabilities)
    uint currentCapabilities() const;

    Q_PROPERTY(uint ModemCapabilities READ modemCapabilities)
    uint modemCapabilities() const;

public Q_SLOTS: // METHODS
Q_SIGNALS: // SIGNALS
    void PropertiesChanged();
};

#endif
