/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./networkmanager-qt/src/dbus/introspection/org.freedesktop.NetworkManager.Device.Gre.xml -a ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.GreAdaptor -i ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.Gre.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.GreAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class GreAdaptor
 */

GreAdaptor::GreAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

GreAdaptor::~GreAdaptor()
{
    // destructor
}

ushort GreAdaptor::inputFlags() const
{
    // get the value of property InputFlags
    return qvariant_cast< ushort >(parent()->property("InputFlags"));
}

uint GreAdaptor::inputKey() const
{
    // get the value of property InputKey
    return qvariant_cast< uint >(parent()->property("InputKey"));
}

QString GreAdaptor::local() const
{
    // get the value of property Local
    return qvariant_cast< QString >(parent()->property("Local"));
}

ushort GreAdaptor::outputFlags() const
{
    // get the value of property OutputFlags
    return qvariant_cast< ushort >(parent()->property("OutputFlags"));
}

uint GreAdaptor::outputKey() const
{
    // get the value of property OutputKey
    return qvariant_cast< uint >(parent()->property("OutputKey"));
}

QDBusObjectPath GreAdaptor::parent() const
{
    // get the value of property Parent
    return qvariant_cast< QDBusObjectPath >(parent()->property("Parent"));
}

bool GreAdaptor::pathMtuDiscovery() const
{
    // get the value of property PathMtuDiscovery
    return qvariant_cast< bool >(parent()->property("PathMtuDiscovery"));
}

QString GreAdaptor::remote() const
{
    // get the value of property Remote
    return qvariant_cast< QString >(parent()->property("Remote"));
}

uchar GreAdaptor::tos() const
{
    // get the value of property Tos
    return qvariant_cast< uchar >(parent()->property("Tos"));
}

uchar GreAdaptor::ttl() const
{
    // get the value of property Ttl
    return qvariant_cast< uchar >(parent()->property("Ttl"));
}

