/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./networkmanager-qt/src/dbus/introspection/org.freedesktop.NetworkManager.Connection.Active.xml -a ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Connection.ActiveAdaptor -i ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Connection.Active.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Connection.ActiveAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class ActiveAdaptor
 */

ActiveAdaptor::ActiveAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

ActiveAdaptor::~ActiveAdaptor()
{
    // destructor
}

QDBusObjectPath ActiveAdaptor::connection() const
{
    // get the value of property Connection
    return qvariant_cast< QDBusObjectPath >(parent()->property("Connection"));
}

bool ActiveAdaptor::default() const
{
    // get the value of property Default
    return qvariant_cast< bool >(parent()->property("Default"));
}

bool ActiveAdaptor::default6() const
{
    // get the value of property Default6
    return qvariant_cast< bool >(parent()->property("Default6"));
}

QList<QDBusObjectPath> ActiveAdaptor::devices() const
{
    // get the value of property Devices
    return qvariant_cast< QList<QDBusObjectPath> >(parent()->property("Devices"));
}

QDBusObjectPath ActiveAdaptor::dhcp4Config() const
{
    // get the value of property Dhcp4Config
    return qvariant_cast< QDBusObjectPath >(parent()->property("Dhcp4Config"));
}

QDBusObjectPath ActiveAdaptor::dhcp6Config() const
{
    // get the value of property Dhcp6Config
    return qvariant_cast< QDBusObjectPath >(parent()->property("Dhcp6Config"));
}

QString ActiveAdaptor::id() const
{
    // get the value of property Id
    return qvariant_cast< QString >(parent()->property("Id"));
}

QDBusObjectPath ActiveAdaptor::ip4Config() const
{
    // get the value of property Ip4Config
    return qvariant_cast< QDBusObjectPath >(parent()->property("Ip4Config"));
}

QDBusObjectPath ActiveAdaptor::ip6Config() const
{
    // get the value of property Ip6Config
    return qvariant_cast< QDBusObjectPath >(parent()->property("Ip6Config"));
}

QDBusObjectPath ActiveAdaptor::master() const
{
    // get the value of property Master
    return qvariant_cast< QDBusObjectPath >(parent()->property("Master"));
}

QDBusObjectPath ActiveAdaptor::specificObject() const
{
    // get the value of property SpecificObject
    return qvariant_cast< QDBusObjectPath >(parent()->property("SpecificObject"));
}

uint ActiveAdaptor::state() const
{
    // get the value of property State
    return qvariant_cast< uint >(parent()->property("State"));
}

QString ActiveAdaptor::type() const
{
    // get the value of property Type
    return qvariant_cast< QString >(parent()->property("Type"));
}

QString ActiveAdaptor::uuid() const
{
    // get the value of property Uuid
    return qvariant_cast< QString >(parent()->property("Uuid"));
}

bool ActiveAdaptor::vpn() const
{
    // get the value of property Vpn
    return qvariant_cast< bool >(parent()->property("Vpn"));
}

