/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./networkmanager-qt/src/dbus/introspection/org.freedesktop.NetworkManager.IP6Config.xml -a ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.IP6ConfigAdaptor -i ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.IP6Config.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.IP6ConfigAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class IP6ConfigAdaptor
 */

IP6ConfigAdaptor::IP6ConfigAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

IP6ConfigAdaptor::~IP6ConfigAdaptor()
{
    // destructor
}

NMVariantMapList IP6ConfigAdaptor::addressData() const
{
    // get the value of property AddressData
    return qvariant_cast< NMVariantMapList >(parent()->property("AddressData"));
}

IpV6DBusAddressList IP6ConfigAdaptor::addresses() const
{
    // get the value of property Addresses
    return qvariant_cast< IpV6DBusAddressList >(parent()->property("Addresses"));
}

QStringList IP6ConfigAdaptor::dnsOptions() const
{
    // get the value of property DnsOptions
    return qvariant_cast< QStringList >(parent()->property("DnsOptions"));
}

int IP6ConfigAdaptor::dnsPriority() const
{
    // get the value of property DnsPriority
    return qvariant_cast< int >(parent()->property("DnsPriority"));
}

QStringList IP6ConfigAdaptor::domains() const
{
    // get the value of property Domains
    return qvariant_cast< QStringList >(parent()->property("Domains"));
}

QString IP6ConfigAdaptor::gateway() const
{
    // get the value of property Gateway
    return qvariant_cast< QString >(parent()->property("Gateway"));
}

IpV6DBusNameservers IP6ConfigAdaptor::nameservers() const
{
    // get the value of property Nameservers
    return qvariant_cast< IpV6DBusNameservers >(parent()->property("Nameservers"));
}

NMVariantMapList IP6ConfigAdaptor::routeData() const
{
    // get the value of property RouteData
    return qvariant_cast< NMVariantMapList >(parent()->property("RouteData"));
}

IpV6DBusRouteList IP6ConfigAdaptor::routes() const
{
    // get the value of property Routes
    return qvariant_cast< IpV6DBusRouteList >(parent()->property("Routes"));
}

QStringList IP6ConfigAdaptor::searches() const
{
    // get the value of property Searches
    return qvariant_cast< QStringList >(parent()->property("Searches"));
}

