/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./networkmanager-qt/src/dbus/introspection/org.freedesktop.NetworkManager.PPP.xml -a ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.PPPAdaptor -i ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.PPP.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ORG_FREEDESKTOP_NETWORKMANAGER_PPPADAPTOR_H
#define ORG_FREEDESKTOP_NETWORKMANAGER_PPPADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.PPP.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.freedesktop.NetworkManager.PPP
 */
class PPPAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.freedesktop.NetworkManager.PPP")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.freedesktop.NetworkManager.PPP\">\n"
"    <annotation value=\"PPP_Manager\" name=\"org.gtk.GDBus.C.Name\"/>\n"
"    <method name=\"NeedSecrets\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"username\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"password\"/>\n"
"    </method>\n"
"    <method name=\"SetIp4Config\">\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"      <arg direction=\"in\" type=\"a{sv}\" name=\"config\"/>\n"
"    </method>\n"
"    <method name=\"SetIp6Config\">\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"      <arg direction=\"in\" type=\"a{sv}\" name=\"config\"/>\n"
"    </method>\n"
"    <method name=\"SetState\">\n"
"      <arg direction=\"in\" type=\"u\" name=\"state\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    PPPAdaptor(QObject *parent);
    virtual ~PPPAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    QString NeedSecrets(QString &password);
    void SetIp4Config(const QVariantMap &config);
    void SetIp6Config(const QVariantMap &config);
    void SetState(uint state);
Q_SIGNALS: // SIGNALS
};

#endif
