/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./networkmanager-qt/src/dbus/introspection/org.freedesktop.NetworkManager.Settings.Connection.xml -a ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Settings.ConnectionAdaptor -i ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Settings.Connection.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ORG_FREEDESKTOP_NETWORKMANAGER_SETTINGS_CONNECTIONADAPTOR_H
#define ORG_FREEDESKTOP_NETWORKMANAGER_SETTINGS_CONNECTIONADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Settings.Connection.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.freedesktop.NetworkManager.Settings.Connection
 */
class ConnectionAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.freedesktop.NetworkManager.Settings.Connection")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.freedesktop.NetworkManager.Settings.Connection\">\n"
"    <method name=\"Update\">\n"
"      <annotation value=\"NMVariantMapMap\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"      <arg direction=\"in\" type=\"a{sa{sv}}\" name=\"properties\"/>\n"
"    </method>\n"
"    <method name=\"UpdateUnsaved\">\n"
"      <annotation value=\"NMVariantMapMap\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"      <arg direction=\"in\" type=\"a{sa{sv}}\" name=\"properties\"/>\n"
"    </method>\n"
"    <method name=\"Delete\"/>\n"
"    <method name=\"GetSettings\">\n"
"      <annotation value=\"NMVariantMapMap\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"      <arg direction=\"out\" type=\"a{sa{sv}}\" name=\"settings\"/>\n"
"    </method>\n"
"    <method name=\"GetSecrets\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"setting_name\"/>\n"
"      <annotation value=\"NMVariantMapMap\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"      <arg direction=\"out\" type=\"a{sa{sv}}\" name=\"secrets\"/>\n"
"    </method>\n"
"    <method name=\"ClearSecrets\"/>\n"
"    <method name=\"Save\"/>\n"
"    <signal name=\"Updated\"/>\n"
"    <signal name=\"Removed\"/>\n"
"    <property access=\"read\" type=\"b\" name=\"Unsaved\"/>\n"
"    <signal name=\"PropertiesChanged\">\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    ConnectionAdaptor(QObject *parent);
    virtual ~ConnectionAdaptor();

public: // PROPERTIES
    Q_PROPERTY(bool Unsaved READ unsaved)
    bool unsaved() const;

public Q_SLOTS: // METHODS
    void ClearSecrets();
    void Delete();
    NMVariantMapMap GetSecrets(const QString &setting_name);
    NMVariantMapMap GetSettings();
    void Save();
    void Update(NMVariantMapMap properties);
    void UpdateUnsaved(NMVariantMapMap properties);
Q_SIGNALS: // SIGNALS
    void PropertiesChanged();
    void Removed();
    void Updated();
};

#endif
