/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./networkmanager-qt/src/dbus/introspection/org.freedesktop.NetworkManager.IP6Config.xml -a ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.IP6ConfigAdaptor -i ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.IP6Config.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ORG_FREEDESKTOP_NETWORKMANAGER_IP6CONFIGADAPTOR_H
#define ORG_FREEDESKTOP_NETWORKMANAGER_IP6CONFIGADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.IP6Config.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.freedesktop.NetworkManager.IP6Config
 */
class IP6ConfigAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.freedesktop.NetworkManager.IP6Config")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.freedesktop.NetworkManager.IP6Config\">\n"
"    <property access=\"read\" type=\"a(ayuay)\" name=\"Addresses\">\n"
"      <annotation value=\"IpV6DBusAddressList\" name=\"org.qtproject.QtDBus.QtTypeName\"/>\n"
"    </property>\n"
"    <property access=\"read\" type=\"aa{sv}\" name=\"AddressData\">\n"
"      <annotation value=\"NMVariantMapList\" name=\"org.qtproject.QtDBus.QtTypeName\"/>\n"
"    </property>\n"
"    <property access=\"read\" type=\"s\" name=\"Gateway\"/>\n"
"    <property access=\"read\" type=\"a(ayuayu)\" name=\"Routes\">\n"
"      <annotation value=\"IpV6DBusRouteList\" name=\"org.qtproject.QtDBus.QtTypeName\"/>\n"
"    </property>\n"
"    <property access=\"read\" type=\"aa{sv}\" name=\"RouteData\">\n"
"      <annotation value=\"NMVariantMapList\" name=\"org.qtproject.QtDBus.QtTypeName\"/>\n"
"    </property>\n"
"    <property access=\"read\" type=\"aay\" name=\"Nameservers\">\n"
"      <annotation value=\"IpV6DBusNameservers\" name=\"org.qtproject.QtDBus.QtTypeName\"/>\n"
"      <annotation value=\"1\" name=\"org.gtk.GDBus.C.ForceGVariant\"/>\n"
"    </property>\n"
"    <property access=\"read\" type=\"as\" name=\"Domains\"/>\n"
"    <property access=\"read\" type=\"as\" name=\"Searches\"/>\n"
"    <property access=\"read\" type=\"as\" name=\"DnsOptions\"/>\n"
"    <property access=\"read\" type=\"i\" name=\"DnsPriority\"/>\n"
"    <signal name=\"PropertiesChanged\">\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    IP6ConfigAdaptor(QObject *parent);
    virtual ~IP6ConfigAdaptor();

public: // PROPERTIES
    Q_PROPERTY(NMVariantMapList AddressData READ addressData)
    NMVariantMapList addressData() const;

    Q_PROPERTY(IpV6DBusAddressList Addresses READ addresses)
    IpV6DBusAddressList addresses() const;

    Q_PROPERTY(QStringList DnsOptions READ dnsOptions)
    QStringList dnsOptions() const;

    Q_PROPERTY(int DnsPriority READ dnsPriority)
    int dnsPriority() const;

    Q_PROPERTY(QStringList Domains READ domains)
    QStringList domains() const;

    Q_PROPERTY(QString Gateway READ gateway)
    QString gateway() const;

    Q_PROPERTY(IpV6DBusNameservers Nameservers READ nameservers)
    IpV6DBusNameservers nameservers() const;

    Q_PROPERTY(NMVariantMapList RouteData READ routeData)
    NMVariantMapList routeData() const;

    Q_PROPERTY(IpV6DBusRouteList Routes READ routes)
    IpV6DBusRouteList routes() const;

    Q_PROPERTY(QStringList Searches READ searches)
    QStringList searches() const;

public Q_SLOTS: // METHODS
Q_SIGNALS: // SIGNALS
    void PropertiesChanged();
};

#endif
