/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./networkmanager-qt/src/dbus/introspection/org.freedesktop.NetworkManager.Device.xml -a ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.DeviceAdaptor -i ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.DeviceAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class DeviceAdaptor
 */

DeviceAdaptor::DeviceAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

DeviceAdaptor::~DeviceAdaptor()
{
    // destructor
}

QDBusObjectPath DeviceAdaptor::activeConnection() const
{
    // get the value of property ActiveConnection
    return qvariant_cast< QDBusObjectPath >(parent()->property("ActiveConnection"));
}

bool DeviceAdaptor::autoconnect() const
{
    // get the value of property Autoconnect
    return qvariant_cast< bool >(parent()->property("Autoconnect"));
}

void DeviceAdaptor::setAutoconnect(bool value)
{
    // set the value of property Autoconnect
    parent()->setProperty("Autoconnect", QVariant::fromValue(value));
}

QList<QDBusObjectPath> DeviceAdaptor::availableConnections() const
{
    // get the value of property AvailableConnections
    return qvariant_cast< QList<QDBusObjectPath> >(parent()->property("AvailableConnections"));
}

uint DeviceAdaptor::capabilities() const
{
    // get the value of property Capabilities
    return qvariant_cast< uint >(parent()->property("Capabilities"));
}

uint DeviceAdaptor::deviceType() const
{
    // get the value of property DeviceType
    return qvariant_cast< uint >(parent()->property("DeviceType"));
}

QDBusObjectPath DeviceAdaptor::dhcp4Config() const
{
    // get the value of property Dhcp4Config
    return qvariant_cast< QDBusObjectPath >(parent()->property("Dhcp4Config"));
}

QDBusObjectPath DeviceAdaptor::dhcp6Config() const
{
    // get the value of property Dhcp6Config
    return qvariant_cast< QDBusObjectPath >(parent()->property("Dhcp6Config"));
}

QString DeviceAdaptor::driver() const
{
    // get the value of property Driver
    return qvariant_cast< QString >(parent()->property("Driver"));
}

QString DeviceAdaptor::driverVersion() const
{
    // get the value of property DriverVersion
    return qvariant_cast< QString >(parent()->property("DriverVersion"));
}

bool DeviceAdaptor::firmwareMissing() const
{
    // get the value of property FirmwareMissing
    return qvariant_cast< bool >(parent()->property("FirmwareMissing"));
}

QString DeviceAdaptor::firmwareVersion() const
{
    // get the value of property FirmwareVersion
    return qvariant_cast< QString >(parent()->property("FirmwareVersion"));
}

QString DeviceAdaptor::interface() const
{
    // get the value of property Interface
    return qvariant_cast< QString >(parent()->property("Interface"));
}

uint DeviceAdaptor::ip4Address() const
{
    // get the value of property Ip4Address
    return qvariant_cast< uint >(parent()->property("Ip4Address"));
}

QDBusObjectPath DeviceAdaptor::ip4Config() const
{
    // get the value of property Ip4Config
    return qvariant_cast< QDBusObjectPath >(parent()->property("Ip4Config"));
}

QDBusObjectPath DeviceAdaptor::ip6Config() const
{
    // get the value of property Ip6Config
    return qvariant_cast< QDBusObjectPath >(parent()->property("Ip6Config"));
}

QString DeviceAdaptor::ipInterface() const
{
    // get the value of property IpInterface
    return qvariant_cast< QString >(parent()->property("IpInterface"));
}

NMVariantMapList DeviceAdaptor::lldpNeighbors() const
{
    // get the value of property LldpNeighbors
    return qvariant_cast< NMVariantMapList >(parent()->property("LldpNeighbors"));
}

bool DeviceAdaptor::managed() const
{
    // get the value of property Managed
    return qvariant_cast< bool >(parent()->property("Managed"));
}

void DeviceAdaptor::setManaged(bool value)
{
    // set the value of property Managed
    parent()->setProperty("Managed", QVariant::fromValue(value));
}

uint DeviceAdaptor::metered() const
{
    // get the value of property Metered
    return qvariant_cast< uint >(parent()->property("Metered"));
}

uint DeviceAdaptor::mtu() const
{
    // get the value of property Mtu
    return qvariant_cast< uint >(parent()->property("Mtu"));
}

bool DeviceAdaptor::nmPluginMissing() const
{
    // get the value of property NmPluginMissing
    return qvariant_cast< bool >(parent()->property("NmPluginMissing"));
}

QString DeviceAdaptor::physicalPortId() const
{
    // get the value of property PhysicalPortId
    return qvariant_cast< QString >(parent()->property("PhysicalPortId"));
}

bool DeviceAdaptor::real() const
{
    // get the value of property Real
    return qvariant_cast< bool >(parent()->property("Real"));
}

uint DeviceAdaptor::state() const
{
    // get the value of property State
    return qvariant_cast< uint >(parent()->property("State"));
}

DeviceDBusStateReason DeviceAdaptor::stateReason() const
{
    // get the value of property StateReason
    return qvariant_cast< DeviceDBusStateReason >(parent()->property("StateReason"));
}

QString DeviceAdaptor::udi() const
{
    // get the value of property Udi
    return qvariant_cast< QString >(parent()->property("Udi"));
}

void DeviceAdaptor::Delete()
{
    // handle method call org.freedesktop.NetworkManager.Device.Delete
    QMetaObject::invokeMethod(parent(), "Delete");
}

void DeviceAdaptor::Disconnect()
{
    // handle method call org.freedesktop.NetworkManager.Device.Disconnect
    QMetaObject::invokeMethod(parent(), "Disconnect");
}

NMVariantMapMap DeviceAdaptor::GetAppliedConnection(uint flags, qulonglong &version_id)
{
    // handle method call org.freedesktop.NetworkManager.Device.GetAppliedConnection
    //return static_cast<YourObjectType *>(parent())->GetAppliedConnection(flags, version_id);
}

void DeviceAdaptor::Reapply(NMVariantMapMap connection, qulonglong version_id, uint flags)
{
    // handle method call org.freedesktop.NetworkManager.Device.Reapply
    QMetaObject::invokeMethod(parent(), "Reapply", Q_ARG(NMVariantMapMap, connection), Q_ARG(qulonglong, version_id), Q_ARG(uint, flags));
}

