/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./networkmanager-qt/src/dbus/introspection/org.freedesktop.NetworkManager.Device.Wireless.xml -a ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.WirelessAdaptor -i ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.Wireless.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ORG_FREEDESKTOP_NETWORKMANAGER_DEVICE_WIRELESSADAPTOR_H
#define ORG_FREEDESKTOP_NETWORKMANAGER_DEVICE_WIRELESSADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.Wireless.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.freedesktop.NetworkManager.Device.Wireless
 */
class WirelessAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.freedesktop.NetworkManager.Device.Wireless")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.freedesktop.NetworkManager.Device.Wireless\">\n"
"    <annotation value=\"DeviceWifi\" name=\"org.gtk.GDBus.C.Name\"/>\n"
"    <method name=\"GetAccessPoints\">\n"
"      <arg direction=\"out\" type=\"ao\" name=\"access_points\"/>\n"
"    </method>\n"
"    <method name=\"GetAllAccessPoints\">\n"
"      <arg direction=\"out\" type=\"ao\" name=\"access_points\"/>\n"
"    </method>\n"
"    <method name=\"RequestScan\">\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"      <arg direction=\"in\" type=\"a{sv}\" name=\"options\"/>\n"
"    </method>\n"
"    <property access=\"read\" type=\"s\" name=\"HwAddress\"/>\n"
"    <property access=\"read\" type=\"s\" name=\"PermHwAddress\"/>\n"
"    <property access=\"read\" type=\"u\" name=\"Mode\"/>\n"
"    <property access=\"read\" type=\"u\" name=\"Bitrate\"/>\n"
"    <property access=\"read\" type=\"ao\" name=\"AccessPoints\"/>\n"
"    <property access=\"read\" type=\"o\" name=\"ActiveAccessPoint\"/>\n"
"    <property access=\"read\" type=\"u\" name=\"WirelessCapabilities\"/>\n"
"    <signal name=\"PropertiesChanged\">\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"    </signal>\n"
"    <signal name=\"AccessPointAdded\">\n"
"      <arg type=\"o\" name=\"access_point\"/>\n"
"    </signal>\n"
"    <signal name=\"AccessPointRemoved\">\n"
"      <arg type=\"o\" name=\"access_point\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    WirelessAdaptor(QObject *parent);
    virtual ~WirelessAdaptor();

public: // PROPERTIES
    Q_PROPERTY(QList<QDBusObjectPath> AccessPoints READ accessPoints)
    QList<QDBusObjectPath> accessPoints() const;

    Q_PROPERTY(QDBusObjectPath ActiveAccessPoint READ activeAccessPoint)
    QDBusObjectPath activeAccessPoint() const;

    Q_PROPERTY(uint Bitrate READ bitrate)
    uint bitrate() const;

    Q_PROPERTY(QString HwAddress READ hwAddress)
    QString hwAddress() const;

    Q_PROPERTY(uint Mode READ mode)
    uint mode() const;

    Q_PROPERTY(QString PermHwAddress READ permHwAddress)
    QString permHwAddress() const;

    Q_PROPERTY(uint WirelessCapabilities READ wirelessCapabilities)
    uint wirelessCapabilities() const;

public Q_SLOTS: // METHODS
    QList<QDBusObjectPath> GetAccessPoints();
    QList<QDBusObjectPath> GetAllAccessPoints();
    void RequestScan(const QVariantMap &options);
Q_SIGNALS: // SIGNALS
    void AccessPointAdded(const QDBusObjectPath &access_point);
    void AccessPointRemoved(const QDBusObjectPath &access_point);
    void PropertiesChanged();
};

#endif
