/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./networkmanager-qt/src/dbus/introspection/org.freedesktop.NetworkManager.Device.Wired.xml -a ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.WiredAdaptor -i ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.Wired.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ORG_FREEDESKTOP_NETWORKMANAGER_DEVICE_WIREDADAPTOR_H
#define ORG_FREEDESKTOP_NETWORKMANAGER_DEVICE_WIREDADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.Wired.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.freedesktop.NetworkManager.Device.Wired
 */
class WiredAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.freedesktop.NetworkManager.Device.Wired")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.freedesktop.NetworkManager.Device.Wired\">\n"
"    <annotation value=\"DeviceEthernet\" name=\"org.gtk.GDBus.C.Name\"/>\n"
"    <property access=\"read\" type=\"s\" name=\"HwAddress\"/>\n"
"    <property access=\"read\" type=\"s\" name=\"PermHwAddress\"/>\n"
"    <property access=\"read\" type=\"u\" name=\"Speed\"/>\n"
"    <property access=\"read\" type=\"as\" name=\"S390Subchannels\"/>\n"
"    <property access=\"read\" type=\"b\" name=\"Carrier\"/>\n"
"    <signal name=\"PropertiesChanged\">\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    WiredAdaptor(QObject *parent);
    virtual ~WiredAdaptor();

public: // PROPERTIES
    Q_PROPERTY(bool Carrier READ carrier)
    bool carrier() const;

    Q_PROPERTY(QString HwAddress READ hwAddress)
    QString hwAddress() const;

    Q_PROPERTY(QString PermHwAddress READ permHwAddress)
    QString permHwAddress() const;

    Q_PROPERTY(QStringList S390Subchannels READ s390Subchannels)
    QStringList s390Subchannels() const;

    Q_PROPERTY(uint Speed READ speed)
    uint speed() const;

public Q_SLOTS: // METHODS
Q_SIGNALS: // SIGNALS
    void PropertiesChanged();
};

#endif
