/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./networkmanager-qt/src/dbus/introspection/org.freedesktop.NetworkManager.Device.Statistics.xml -a ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.StatisticsAdaptor -i ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.Statistics.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ORG_FREEDESKTOP_NETWORKMANAGER_DEVICE_STATISTICSADAPTOR_H
#define ORG_FREEDESKTOP_NETWORKMANAGER_DEVICE_STATISTICSADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.Statistics.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.freedesktop.NetworkManager.Device.Statistics
 */
class StatisticsAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.freedesktop.NetworkManager.Device.Statistics")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.freedesktop.NetworkManager.Device.Statistics\">\n"
"    <property access=\"readwrite\" type=\"u\" name=\"RefreshRateMs\"/>\n"
"    <property access=\"read\" type=\"t\" name=\"TxBytes\"/>\n"
"    <property access=\"read\" type=\"t\" name=\"RxBytes\"/>\n"
"    <signal name=\"PropertiesChanged\">\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    StatisticsAdaptor(QObject *parent);
    virtual ~StatisticsAdaptor();

public: // PROPERTIES
    Q_PROPERTY(uint RefreshRateMs READ refreshRateMs WRITE setRefreshRateMs)
    uint refreshRateMs() const;
    void setRefreshRateMs(uint value);

    Q_PROPERTY(qulonglong RxBytes READ rxBytes)
    qulonglong rxBytes() const;

    Q_PROPERTY(qulonglong TxBytes READ txBytes)
    qulonglong txBytes() const;

public Q_SLOTS: // METHODS
Q_SIGNALS: // SIGNALS
    void PropertiesChanged();
};

#endif
