/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./networkmanager-qt/src/dbus/introspection/org.freedesktop.NetworkManager.AgentManager.xml -a ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.AgentManagerAdaptor -i ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.AgentManager.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.AgentManagerAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class AgentManagerAdaptor
 */

AgentManagerAdaptor::AgentManagerAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

AgentManagerAdaptor::~AgentManagerAdaptor()
{
    // destructor
}

void AgentManagerAdaptor::Register(const QString &identifier)
{
    // handle method call org.freedesktop.NetworkManager.AgentManager.Register
    QMetaObject::invokeMethod(parent(), "Register", Q_ARG(QString, identifier));
}

void AgentManagerAdaptor::RegisterWithCapabilities(const QString &identifier, uint capabilities)
{
    // handle method call org.freedesktop.NetworkManager.AgentManager.RegisterWithCapabilities
    QMetaObject::invokeMethod(parent(), "RegisterWithCapabilities", Q_ARG(QString, identifier), Q_ARG(uint, capabilities));
}

void AgentManagerAdaptor::Unregister()
{
    // handle method call org.freedesktop.NetworkManager.AgentManager.Unregister
    QMetaObject::invokeMethod(parent(), "Unregister");
}

