/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./networkmanager-qt/src/dbus/introspection/org.freedesktop.NetworkManager.Device.Adsl.xml -a ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.AdslAdaptor -i ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.Adsl.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.AdslAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class AdslAdaptor
 */

AdslAdaptor::AdslAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

AdslAdaptor::~AdslAdaptor()
{
    // destructor
}

bool AdslAdaptor::carrier() const
{
    // get the value of property Carrier
    return qvariant_cast< bool >(parent()->property("Carrier"));
}

