/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./networkmanager-qt/src/dbus/introspection/org.freedesktop.NetworkManager.DnsManager.xml -a ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.DnsManagerAdaptor -i ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.DnsManager.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ORG_FREEDESKTOP_NETWORKMANAGER_DNSMANAGERADAPTOR_H
#define ORG_FREEDESKTOP_NETWORKMANAGER_DNSMANAGERADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.DnsManager.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.freedesktop.NetworkManager.DnsManager
 */
class DnsManagerAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.freedesktop.NetworkManager.DnsManager")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.freedesktop.NetworkManager.DnsManager\">\n"
"    <property access=\"read\" type=\"s\" name=\"Mode\"/>\n"
"    <property access=\"read\" type=\"s\" name=\"RcManager\"/>\n"
"    <property access=\"read\" type=\"aa{sv}\" name=\"Configuration\">\n"
"      <annotation value=\"NMVariantMapList\" name=\"org.qtproject.QtDBus.QtTypeName\"/>\n"
"    </property>\n"
"  </interface>\n"
        "")
public:
    DnsManagerAdaptor(QObject *parent);
    virtual ~DnsManagerAdaptor();

public: // PROPERTIES
    Q_PROPERTY(NMVariantMapList Configuration READ configuration)
    NMVariantMapList configuration() const;

    Q_PROPERTY(QString Mode READ mode)
    QString mode() const;

    Q_PROPERTY(QString RcManager READ rcManager)
    QString rcManager() const;

public Q_SLOTS: // METHODS
Q_SIGNALS: // SIGNALS
};

#endif
