/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./networkmanager-qt/src/dbus/introspection/org.freedesktop.NetworkManager.Device.xml -a ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.DeviceAdaptor -i ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ORG_FREEDESKTOP_NETWORKMANAGER_DEVICEADAPTOR_H
#define ORG_FREEDESKTOP_NETWORKMANAGER_DEVICEADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.freedesktop.NetworkManager.Device
 */
class DeviceAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.freedesktop.NetworkManager.Device")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.freedesktop.NetworkManager.Device\">\n"
"    <property access=\"read\" type=\"s\" name=\"Udi\"/>\n"
"    <property access=\"read\" type=\"s\" name=\"Interface\"/>\n"
"    <property access=\"read\" type=\"s\" name=\"IpInterface\"/>\n"
"    <property access=\"read\" type=\"s\" name=\"Driver\"/>\n"
"    <property access=\"read\" type=\"s\" name=\"DriverVersion\"/>\n"
"    <property access=\"read\" type=\"s\" name=\"FirmwareVersion\"/>\n"
"    <property access=\"read\" type=\"u\" name=\"Capabilities\"/>\n"
"    <property access=\"read\" type=\"u\" name=\"Ip4Address\"/>\n"
"    <property access=\"read\" type=\"u\" name=\"State\"/>\n"
"    <property access=\"read\" type=\"(uu)\" name=\"StateReason\">\n"
"      <annotation value=\"DeviceDBusStateReason\" name=\"org.qtproject.QtDBus.QtTypeName\"/>\n"
"    </property>\n"
"    <property access=\"read\" type=\"o\" name=\"ActiveConnection\"/>\n"
"    <property access=\"read\" type=\"o\" name=\"Ip4Config\"/>\n"
"    <property access=\"read\" type=\"o\" name=\"Dhcp4Config\"/>\n"
"    <property access=\"read\" type=\"o\" name=\"Ip6Config\"/>\n"
"    <property access=\"read\" type=\"o\" name=\"Dhcp6Config\"/>\n"
"    <property access=\"readwrite\" type=\"b\" name=\"Managed\"/>\n"
"    <property access=\"readwrite\" type=\"b\" name=\"Autoconnect\"/>\n"
"    <property access=\"read\" type=\"b\" name=\"FirmwareMissing\"/>\n"
"    <property access=\"read\" type=\"b\" name=\"NmPluginMissing\"/>\n"
"    <property access=\"read\" type=\"u\" name=\"DeviceType\"/>\n"
"    <property access=\"read\" type=\"ao\" name=\"AvailableConnections\"/>\n"
"    <property access=\"read\" type=\"s\" name=\"PhysicalPortId\"/>\n"
"    <property access=\"read\" type=\"u\" name=\"Mtu\"/>\n"
"    <property access=\"read\" type=\"u\" name=\"Metered\"/>\n"
"    <property access=\"read\" type=\"aa{sv}\" name=\"LldpNeighbors\">\n"
"      <annotation value=\"NMVariantMapList\" name=\"org.qtproject.QtDBus.QtTypeName\"/>\n"
"    </property>\n"
"    <property access=\"read\" type=\"b\" name=\"Real\"/>\n"
"    <method name=\"Reapply\">\n"
"      <annotation value=\"NMVariantMapMap\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"      <arg direction=\"in\" type=\"a{sa{sv}}\" name=\"connection\"/>\n"
"      <arg direction=\"in\" type=\"t\" name=\"version_id\"/>\n"
"      <arg direction=\"in\" type=\"u\" name=\"flags\"/>\n"
"    </method>\n"
"    <method name=\"GetAppliedConnection\">\n"
"      <arg direction=\"in\" type=\"u\" name=\"flags\"/>\n"
"      <annotation value=\"NMVariantMapMap\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"      <arg direction=\"out\" type=\"a{sa{sv}}\" name=\"connection\"/>\n"
"      <arg direction=\"out\" type=\"t\" name=\"version_id\"/>\n"
"    </method>\n"
"    <method name=\"Disconnect\"/>\n"
"    <method name=\"Delete\"/>\n"
"    <signal name=\"StateChanged\">\n"
"      <arg type=\"u\" name=\"new_state\"/>\n"
"      <arg type=\"u\" name=\"old_state\"/>\n"
"      <arg type=\"u\" name=\"reason\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    DeviceAdaptor(QObject *parent);
    virtual ~DeviceAdaptor();

public: // PROPERTIES
    Q_PROPERTY(QDBusObjectPath ActiveConnection READ activeConnection)
    QDBusObjectPath activeConnection() const;

    Q_PROPERTY(bool Autoconnect READ autoconnect WRITE setAutoconnect)
    bool autoconnect() const;
    void setAutoconnect(bool value);

    Q_PROPERTY(QList<QDBusObjectPath> AvailableConnections READ availableConnections)
    QList<QDBusObjectPath> availableConnections() const;

    Q_PROPERTY(uint Capabilities READ capabilities)
    uint capabilities() const;

    Q_PROPERTY(uint DeviceType READ deviceType)
    uint deviceType() const;

    Q_PROPERTY(QDBusObjectPath Dhcp4Config READ dhcp4Config)
    QDBusObjectPath dhcp4Config() const;

    Q_PROPERTY(QDBusObjectPath Dhcp6Config READ dhcp6Config)
    QDBusObjectPath dhcp6Config() const;

    Q_PROPERTY(QString Driver READ driver)
    QString driver() const;

    Q_PROPERTY(QString DriverVersion READ driverVersion)
    QString driverVersion() const;

    Q_PROPERTY(bool FirmwareMissing READ firmwareMissing)
    bool firmwareMissing() const;

    Q_PROPERTY(QString FirmwareVersion READ firmwareVersion)
    QString firmwareVersion() const;

    Q_PROPERTY(QString Interface READ interface)
    QString interface() const;

    Q_PROPERTY(uint Ip4Address READ ip4Address)
    uint ip4Address() const;

    Q_PROPERTY(QDBusObjectPath Ip4Config READ ip4Config)
    QDBusObjectPath ip4Config() const;

    Q_PROPERTY(QDBusObjectPath Ip6Config READ ip6Config)
    QDBusObjectPath ip6Config() const;

    Q_PROPERTY(QString IpInterface READ ipInterface)
    QString ipInterface() const;

    Q_PROPERTY(NMVariantMapList LldpNeighbors READ lldpNeighbors)
    NMVariantMapList lldpNeighbors() const;

    Q_PROPERTY(bool Managed READ managed WRITE setManaged)
    bool managed() const;
    void setManaged(bool value);

    Q_PROPERTY(uint Metered READ metered)
    uint metered() const;

    Q_PROPERTY(uint Mtu READ mtu)
    uint mtu() const;

    Q_PROPERTY(bool NmPluginMissing READ nmPluginMissing)
    bool nmPluginMissing() const;

    Q_PROPERTY(QString PhysicalPortId READ physicalPortId)
    QString physicalPortId() const;

    Q_PROPERTY(bool Real READ real)
    bool real() const;

    Q_PROPERTY(uint State READ state)
    uint state() const;

    Q_PROPERTY(DeviceDBusStateReason StateReason READ stateReason)
    DeviceDBusStateReason stateReason() const;

    Q_PROPERTY(QString Udi READ udi)
    QString udi() const;

public Q_SLOTS: // METHODS
    void Delete();
    void Disconnect();
    NMVariantMapMap GetAppliedConnection(uint flags, qulonglong &version_id);
    void Reapply(NMVariantMapMap connection, qulonglong version_id, uint flags);
Q_SIGNALS: // SIGNALS
    void StateChanged(uint new_state, uint old_state, uint reason);
};

#endif
