/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./networkmanager-qt/src/dbus/introspection/org.freedesktop.NetworkManager.Device.Tun.xml -a ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.TunAdaptor -i ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.Tun.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ORG_FREEDESKTOP_NETWORKMANAGER_DEVICE_TUNADAPTOR_H
#define ORG_FREEDESKTOP_NETWORKMANAGER_DEVICE_TUNADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.Tun.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.freedesktop.NetworkManager.Device.Tun
 */
class TunAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.freedesktop.NetworkManager.Device.Tun")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.freedesktop.NetworkManager.Device.Tun\">\n"
"    <property access=\"read\" type=\"x\" name=\"Owner\"/>\n"
"    <property access=\"read\" type=\"x\" name=\"Group\"/>\n"
"    <property access=\"read\" type=\"s\" name=\"Mode\"/>\n"
"    <property access=\"read\" type=\"b\" name=\"NoPi\"/>\n"
"    <property access=\"read\" type=\"b\" name=\"VnetHdr\"/>\n"
"    <property access=\"read\" type=\"b\" name=\"MultiQueue\"/>\n"
"    <property access=\"read\" type=\"s\" name=\"HwAddress\"/>\n"
"    <signal name=\"PropertiesChanged\">\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    TunAdaptor(QObject *parent);
    virtual ~TunAdaptor();

public: // PROPERTIES
    Q_PROPERTY(qlonglong Group READ group)
    qlonglong group() const;

    Q_PROPERTY(QString HwAddress READ hwAddress)
    QString hwAddress() const;

    Q_PROPERTY(QString Mode READ mode)
    QString mode() const;

    Q_PROPERTY(bool MultiQueue READ multiQueue)
    bool multiQueue() const;

    Q_PROPERTY(bool NoPi READ noPi)
    bool noPi() const;

    Q_PROPERTY(qlonglong Owner READ owner)
    qlonglong owner() const;

    Q_PROPERTY(bool VnetHdr READ vnetHdr)
    bool vnetHdr() const;

public Q_SLOTS: // METHODS
Q_SIGNALS: // SIGNALS
    void PropertiesChanged();
};

#endif
