/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./networkmanager-qt/src/dbus/introspection/org.freedesktop.NetworkManager.Settings.xml -a ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.SettingsAdaptor -i ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Settings.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ORG_FREEDESKTOP_NETWORKMANAGER_SETTINGSADAPTOR_H
#define ORG_FREEDESKTOP_NETWORKMANAGER_SETTINGSADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Settings.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.freedesktop.NetworkManager.Settings
 */
class SettingsAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.freedesktop.NetworkManager.Settings")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.freedesktop.NetworkManager.Settings\">\n"
"    <method name=\"ListConnections\">\n"
"      <arg direction=\"out\" type=\"ao\" name=\"connections\"/>\n"
"    </method>\n"
"    <method name=\"GetConnectionByUuid\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"uuid\"/>\n"
"      <arg direction=\"out\" type=\"o\" name=\"connection\"/>\n"
"    </method>\n"
"    <method name=\"AddConnection\">\n"
"      <annotation value=\"NMVariantMapMap\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"      <arg direction=\"in\" type=\"a{sa{sv}}\" name=\"connection\"/>\n"
"      <arg direction=\"out\" type=\"o\" name=\"path\"/>\n"
"    </method>\n"
"    <method name=\"AddConnectionUnsaved\">\n"
"      <annotation value=\"NMVariantMapMap\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"      <arg direction=\"in\" type=\"a{sa{sv}}\" name=\"connection\"/>\n"
"      <arg direction=\"out\" type=\"o\" name=\"path\"/>\n"
"    </method>\n"
"    <method name=\"LoadConnections\">\n"
"      <arg direction=\"in\" type=\"as\" name=\"filenames\"/>\n"
"      <arg direction=\"out\" type=\"b\" name=\"status\"/>\n"
"      <arg direction=\"out\" type=\"as\" name=\"failures\"/>\n"
"    </method>\n"
"    <method name=\"ReloadConnections\">\n"
"      <arg direction=\"out\" type=\"b\" name=\"status\"/>\n"
"    </method>\n"
"    <method name=\"SaveHostname\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"hostname\"/>\n"
"    </method>\n"
"    <property access=\"read\" type=\"ao\" name=\"Connections\"/>\n"
"    <property access=\"read\" type=\"s\" name=\"Hostname\"/>\n"
"    <property access=\"read\" type=\"b\" name=\"CanModify\"/>\n"
"    <signal name=\"PropertiesChanged\">\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"    </signal>\n"
"    <signal name=\"NewConnection\">\n"
"      <arg type=\"o\" name=\"connection\"/>\n"
"    </signal>\n"
"    <signal name=\"ConnectionRemoved\">\n"
"      <arg type=\"o\" name=\"connection\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    SettingsAdaptor(QObject *parent);
    virtual ~SettingsAdaptor();

public: // PROPERTIES
    Q_PROPERTY(bool CanModify READ canModify)
    bool canModify() const;

    Q_PROPERTY(QList<QDBusObjectPath> Connections READ connections)
    QList<QDBusObjectPath> connections() const;

    Q_PROPERTY(QString Hostname READ hostname)
    QString hostname() const;

public Q_SLOTS: // METHODS
    QDBusObjectPath AddConnection(NMVariantMapMap connection);
    QDBusObjectPath AddConnectionUnsaved(NMVariantMapMap connection);
    QDBusObjectPath GetConnectionByUuid(const QString &uuid);
    QList<QDBusObjectPath> ListConnections();
    bool LoadConnections(const QStringList &filenames, QStringList &failures);
    bool ReloadConnections();
    void SaveHostname(const QString &hostname);
Q_SIGNALS: // SIGNALS
    void ConnectionRemoved(const QDBusObjectPath &connection);
    void NewConnection(const QDBusObjectPath &connection);
    void PropertiesChanged();
};

#endif
