/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./networkmanager-qt/src/dbus/introspection/org.freedesktop.NetworkManager.Device.Macvlan.xml -a ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.MacvlanAdaptor -i ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.Macvlan.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ORG_FREEDESKTOP_NETWORKMANAGER_DEVICE_MACVLANADAPTOR_H
#define ORG_FREEDESKTOP_NETWORKMANAGER_DEVICE_MACVLANADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.Macvlan.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.freedesktop.NetworkManager.Device.Macvlan
 */
class MacvlanAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.freedesktop.NetworkManager.Device.Macvlan")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.freedesktop.NetworkManager.Device.Macvlan\">\n"
"    <property access=\"read\" type=\"o\" name=\"Parent\"/>\n"
"    <property access=\"read\" type=\"s\" name=\"Mode\"/>\n"
"    <property access=\"read\" type=\"b\" name=\"NoPromisc\"/>\n"
"    <property access=\"read\" type=\"b\" name=\"Tap\"/>\n"
"    <signal name=\"PropertiesChanged\">\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    MacvlanAdaptor(QObject *parent);
    virtual ~MacvlanAdaptor();

public: // PROPERTIES
    Q_PROPERTY(QString Mode READ mode)
    QString mode() const;

    Q_PROPERTY(bool NoPromisc READ noPromisc)
    bool noPromisc() const;

    Q_PROPERTY(QDBusObjectPath Parent READ parent)
    QDBusObjectPath parent() const;

    Q_PROPERTY(bool Tap READ tap)
    bool tap() const;

public Q_SLOTS: // METHODS
Q_SIGNALS: // SIGNALS
    void PropertiesChanged();
};

#endif
