/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./networkmanager-qt/src/dbus/introspection/org.freedesktop.NetworkManager.Settings.xml -a ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.SettingsAdaptor -i ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Settings.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.SettingsAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class SettingsAdaptor
 */

SettingsAdaptor::SettingsAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

SettingsAdaptor::~SettingsAdaptor()
{
    // destructor
}

bool SettingsAdaptor::canModify() const
{
    // get the value of property CanModify
    return qvariant_cast< bool >(parent()->property("CanModify"));
}

QList<QDBusObjectPath> SettingsAdaptor::connections() const
{
    // get the value of property Connections
    return qvariant_cast< QList<QDBusObjectPath> >(parent()->property("Connections"));
}

QString SettingsAdaptor::hostname() const
{
    // get the value of property Hostname
    return qvariant_cast< QString >(parent()->property("Hostname"));
}

QDBusObjectPath SettingsAdaptor::AddConnection(NMVariantMapMap connection)
{
    // handle method call org.freedesktop.NetworkManager.Settings.AddConnection
    QDBusObjectPath path;
    QMetaObject::invokeMethod(parent(), "AddConnection", Q_RETURN_ARG(QDBusObjectPath, path), Q_ARG(NMVariantMapMap, connection));
    return path;
}

QDBusObjectPath SettingsAdaptor::AddConnectionUnsaved(NMVariantMapMap connection)
{
    // handle method call org.freedesktop.NetworkManager.Settings.AddConnectionUnsaved
    QDBusObjectPath path;
    QMetaObject::invokeMethod(parent(), "AddConnectionUnsaved", Q_RETURN_ARG(QDBusObjectPath, path), Q_ARG(NMVariantMapMap, connection));
    return path;
}

QDBusObjectPath SettingsAdaptor::GetConnectionByUuid(const QString &uuid)
{
    // handle method call org.freedesktop.NetworkManager.Settings.GetConnectionByUuid
    QDBusObjectPath connection;
    QMetaObject::invokeMethod(parent(), "GetConnectionByUuid", Q_RETURN_ARG(QDBusObjectPath, connection), Q_ARG(QString, uuid));
    return connection;
}

QList<QDBusObjectPath> SettingsAdaptor::ListConnections()
{
    // handle method call org.freedesktop.NetworkManager.Settings.ListConnections
    QList<QDBusObjectPath> connections;
    QMetaObject::invokeMethod(parent(), "ListConnections", Q_RETURN_ARG(QList<QDBusObjectPath>, connections));
    return connections;
}

bool SettingsAdaptor::LoadConnections(const QStringList &filenames, QStringList &failures)
{
    // handle method call org.freedesktop.NetworkManager.Settings.LoadConnections
    //return static_cast<YourObjectType *>(parent())->LoadConnections(filenames, failures);
}

bool SettingsAdaptor::ReloadConnections()
{
    // handle method call org.freedesktop.NetworkManager.Settings.ReloadConnections
    bool status;
    QMetaObject::invokeMethod(parent(), "ReloadConnections", Q_RETURN_ARG(bool, status));
    return status;
}

void SettingsAdaptor::SaveHostname(const QString &hostname)
{
    // handle method call org.freedesktop.NetworkManager.Settings.SaveHostname
    QMetaObject::invokeMethod(parent(), "SaveHostname", Q_ARG(QString, hostname));
}

