/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./networkmanager-qt/src/dbus/introspection/org.freedesktop.NetworkManager.Device.WiMax.xml -a ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.WiMaxAdaptor -i ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.WiMax.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ORG_FREEDESKTOP_NETWORKMANAGER_DEVICE_WIMAXADAPTOR_H
#define ORG_FREEDESKTOP_NETWORKMANAGER_DEVICE_WIMAXADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.WiMax.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.freedesktop.NetworkManager.Device.WiMax
 */
class WiMaxAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.freedesktop.NetworkManager.Device.WiMax")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.freedesktop.NetworkManager.Device.WiMax\">\n"
"    <method name=\"GetNspList\">\n"
"      <arg direction=\"out\" type=\"ao\" name=\"nsps\"/>\n"
"    </method>\n"
"    <property access=\"read\" type=\"ao\" name=\"Nsps\"/>\n"
"    <property access=\"read\" type=\"s\" name=\"HwAddress\"/>\n"
"    <property access=\"read\" type=\"u\" name=\"CenterFrequency\"/>\n"
"    <property access=\"read\" type=\"i\" name=\"Rssi\"/>\n"
"    <property access=\"read\" type=\"i\" name=\"Cinr\"/>\n"
"    <property access=\"read\" type=\"i\" name=\"TxPower\"/>\n"
"    <property access=\"read\" type=\"s\" name=\"Bsid\"/>\n"
"    <property access=\"read\" type=\"o\" name=\"ActiveNsp\"/>\n"
"    <signal name=\"PropertiesChanged\">\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"    </signal>\n"
"    <signal name=\"NspAdded\">\n"
"      <arg type=\"o\" name=\"nsp\"/>\n"
"    </signal>\n"
"    <signal name=\"NspRemoved\">\n"
"      <arg type=\"o\" name=\"nsp\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    WiMaxAdaptor(QObject *parent);
    virtual ~WiMaxAdaptor();

public: // PROPERTIES
    Q_PROPERTY(QDBusObjectPath ActiveNsp READ activeNsp)
    QDBusObjectPath activeNsp() const;

    Q_PROPERTY(QString Bsid READ bsid)
    QString bsid() const;

    Q_PROPERTY(uint CenterFrequency READ centerFrequency)
    uint centerFrequency() const;

    Q_PROPERTY(int Cinr READ cinr)
    int cinr() const;

    Q_PROPERTY(QString HwAddress READ hwAddress)
    QString hwAddress() const;

    Q_PROPERTY(QList<QDBusObjectPath> Nsps READ nsps)
    QList<QDBusObjectPath> nsps() const;

    Q_PROPERTY(int Rssi READ rssi)
    int rssi() const;

    Q_PROPERTY(int TxPower READ txPower)
    int txPower() const;

public Q_SLOTS: // METHODS
    QList<QDBusObjectPath> GetNspList();
Q_SIGNALS: // SIGNALS
    void NspAdded(const QDBusObjectPath &nsp);
    void NspRemoved(const QDBusObjectPath &nsp);
    void PropertiesChanged();
};

#endif
