/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./networkmanager-qt/src/dbus/introspection/org.freedesktop.NetworkManager.Device.Tun.xml -a ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.TunAdaptor -i ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.Tun.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.TunAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class TunAdaptor
 */

TunAdaptor::TunAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

TunAdaptor::~TunAdaptor()
{
    // destructor
}

qlonglong TunAdaptor::group() const
{
    // get the value of property Group
    return qvariant_cast< qlonglong >(parent()->property("Group"));
}

QString TunAdaptor::hwAddress() const
{
    // get the value of property HwAddress
    return qvariant_cast< QString >(parent()->property("HwAddress"));
}

QString TunAdaptor::mode() const
{
    // get the value of property Mode
    return qvariant_cast< QString >(parent()->property("Mode"));
}

bool TunAdaptor::multiQueue() const
{
    // get the value of property MultiQueue
    return qvariant_cast< bool >(parent()->property("MultiQueue"));
}

bool TunAdaptor::noPi() const
{
    // get the value of property NoPi
    return qvariant_cast< bool >(parent()->property("NoPi"));
}

qlonglong TunAdaptor::owner() const
{
    // get the value of property Owner
    return qvariant_cast< qlonglong >(parent()->property("Owner"));
}

bool TunAdaptor::vnetHdr() const
{
    // get the value of property VnetHdr
    return qvariant_cast< bool >(parent()->property("VnetHdr"));
}

