/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./networkmanager-qt/src/dbus/introspection/org.freedesktop.NetworkManager.SecretAgent.xml -a ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.SecretAgentAdaptor -i ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.SecretAgent.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.SecretAgentAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class SecretAgentAdaptor
 */

SecretAgentAdaptor::SecretAgentAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

SecretAgentAdaptor::~SecretAgentAdaptor()
{
    // destructor
}

void SecretAgentAdaptor::CancelGetSecrets(const QDBusObjectPath &connection_path, const QString &setting_name)
{
    // handle method call org.freedesktop.NetworkManager.SecretAgent.CancelGetSecrets
    QMetaObject::invokeMethod(parent(), "CancelGetSecrets", Q_ARG(QDBusObjectPath, connection_path), Q_ARG(QString, setting_name));
}

void SecretAgentAdaptor::DeleteSecrets(NMVariantMapMap connection, const QDBusObjectPath &connection_path)
{
    // handle method call org.freedesktop.NetworkManager.SecretAgent.DeleteSecrets
    QMetaObject::invokeMethod(parent(), "DeleteSecrets", Q_ARG(NMVariantMapMap, connection), Q_ARG(QDBusObjectPath, connection_path));
}

NMVariantMapMap SecretAgentAdaptor::GetSecrets(NMVariantMapMap connection, const QDBusObjectPath &connection_path, const QString &setting_name, const QStringList &hints, uint flags)
{
    // handle method call org.freedesktop.NetworkManager.SecretAgent.GetSecrets
    NMVariantMapMap secrets;
    QMetaObject::invokeMethod(parent(), "GetSecrets", Q_RETURN_ARG(NMVariantMapMap, secrets), Q_ARG(NMVariantMapMap, connection), Q_ARG(QDBusObjectPath, connection_path), Q_ARG(QString, setting_name), Q_ARG(QStringList, hints), Q_ARG(uint, flags));
    return secrets;
}

void SecretAgentAdaptor::SaveSecrets(NMVariantMapMap connection, const QDBusObjectPath &connection_path)
{
    // handle method call org.freedesktop.NetworkManager.SecretAgent.SaveSecrets
    QMetaObject::invokeMethod(parent(), "SaveSecrets", Q_ARG(NMVariantMapMap, connection), Q_ARG(QDBusObjectPath, connection_path));
}

