/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./networkmanager-qt/src/dbus/introspection/org.freedesktop.NetworkManager.Device.IPTunnel.xml -a ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.IPTunnelAdaptor -i ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.IPTunnel.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Device.IPTunnelAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class IPTunnelAdaptor
 */

IPTunnelAdaptor::IPTunnelAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

IPTunnelAdaptor::~IPTunnelAdaptor()
{
    // destructor
}

uchar IPTunnelAdaptor::encapsulationLimit() const
{
    // get the value of property EncapsulationLimit
    return qvariant_cast< uchar >(parent()->property("EncapsulationLimit"));
}

uint IPTunnelAdaptor::flowLabel() const
{
    // get the value of property FlowLabel
    return qvariant_cast< uint >(parent()->property("FlowLabel"));
}

QString IPTunnelAdaptor::inputKey() const
{
    // get the value of property InputKey
    return qvariant_cast< QString >(parent()->property("InputKey"));
}

QString IPTunnelAdaptor::local() const
{
    // get the value of property Local
    return qvariant_cast< QString >(parent()->property("Local"));
}

uint IPTunnelAdaptor::mode() const
{
    // get the value of property Mode
    return qvariant_cast< uint >(parent()->property("Mode"));
}

QString IPTunnelAdaptor::outputKey() const
{
    // get the value of property OutputKey
    return qvariant_cast< QString >(parent()->property("OutputKey"));
}

QDBusObjectPath IPTunnelAdaptor::parent() const
{
    // get the value of property Parent
    return qvariant_cast< QDBusObjectPath >(parent()->property("Parent"));
}

bool IPTunnelAdaptor::pathMtuDiscovery() const
{
    // get the value of property PathMtuDiscovery
    return qvariant_cast< bool >(parent()->property("PathMtuDiscovery"));
}

QString IPTunnelAdaptor::remote() const
{
    // get the value of property Remote
    return qvariant_cast< QString >(parent()->property("Remote"));
}

uchar IPTunnelAdaptor::tos() const
{
    // get the value of property Tos
    return qvariant_cast< uchar >(parent()->property("Tos"));
}

uchar IPTunnelAdaptor::ttl() const
{
    // get the value of property Ttl
    return qvariant_cast< uchar >(parent()->property("Ttl"));
}

