/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./networkmanager-qt/src/dbus/introspection/org.freedesktop.NetworkManager.WiMax.Nsp.xml -a ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.WiMax.NspAdaptor -i ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.WiMax.Nsp.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ORG_FREEDESKTOP_NETWORKMANAGER_WIMAX_NSPADAPTOR_H
#define ORG_FREEDESKTOP_NETWORKMANAGER_WIMAX_NSPADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.WiMax.Nsp.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.freedesktop.NetworkManager.WiMax.Nsp
 */
class NspAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.freedesktop.NetworkManager.WiMax.Nsp")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.freedesktop.NetworkManager.WiMax.Nsp\">\n"
"    <property access=\"read\" type=\"s\" name=\"Name\"/>\n"
"    <property access=\"read\" type=\"u\" name=\"SignalQuality\"/>\n"
"    <property access=\"read\" type=\"u\" name=\"NetworkType\"/>\n"
"    <signal name=\"PropertiesChanged\">\n"
"      <annotation value=\"NMVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    NspAdaptor(QObject *parent);
    virtual ~NspAdaptor();

public: // PROPERTIES
    Q_PROPERTY(QString Name READ name)
    QString name() const;

    Q_PROPERTY(uint NetworkType READ networkType)
    uint networkType() const;

    Q_PROPERTY(uint SignalQuality READ signalQuality)
    uint signalQuality() const;

public Q_SLOTS: // METHODS
Q_SIGNALS: // SIGNALS
    void PropertiesChanged();
};

#endif
