/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./networkmanager-qt/src/dbus/introspection/org.freedesktop.NetworkManager.Connection.Active.xml -a ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Connection.ActiveAdaptor -i ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Connection.Active.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ORG_FREEDESKTOP_NETWORKMANAGER_CONNECTION_ACTIVEADAPTOR_H
#define ORG_FREEDESKTOP_NETWORKMANAGER_CONNECTION_ACTIVEADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.Connection.Active.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.freedesktop.NetworkManager.Connection.Active
 */
class ActiveAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.freedesktop.NetworkManager.Connection.Active")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.freedesktop.NetworkManager.Connection.Active\">\n"
"    <annotation value=\"ActiveConnection\" name=\"org.gtk.GDBus.C.Name\"/>\n"
"    <property access=\"read\" type=\"o\" name=\"Connection\"/>\n"
"    <property access=\"read\" type=\"o\" name=\"SpecificObject\"/>\n"
"    <property access=\"read\" type=\"s\" name=\"Id\"/>\n"
"    <property access=\"read\" type=\"s\" name=\"Uuid\"/>\n"
"    <property access=\"read\" type=\"s\" name=\"Type\"/>\n"
"    <property access=\"read\" type=\"ao\" name=\"Devices\"/>\n"
"    <property access=\"read\" type=\"u\" name=\"State\"/>\n"
"    <signal name=\"StateChanged\">\n"
"      <arg type=\"u\" name=\"state\"/>\n"
"      <arg type=\"u\" name=\"reason\"/>\n"
"    </signal>\n"
"    <property access=\"read\" type=\"b\" name=\"Default\"/>\n"
"    <property access=\"read\" type=\"o\" name=\"Ip4Config\"/>\n"
"    <property access=\"read\" type=\"o\" name=\"Dhcp4Config\"/>\n"
"    <property access=\"read\" type=\"b\" name=\"Default6\"/>\n"
"    <property access=\"read\" type=\"o\" name=\"Ip6Config\"/>\n"
"    <property access=\"read\" type=\"o\" name=\"Dhcp6Config\"/>\n"
"    <property access=\"read\" type=\"b\" name=\"Vpn\"/>\n"
"    <property access=\"read\" type=\"o\" name=\"Master\"/>\n"
"    <signal name=\"PropertiesChanged\">\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    ActiveAdaptor(QObject *parent);
    virtual ~ActiveAdaptor();

public: // PROPERTIES
    Q_PROPERTY(QDBusObjectPath Connection READ connection)
    QDBusObjectPath connection() const;

    Q_PROPERTY(bool Default READ default)
    bool default() const;

    Q_PROPERTY(bool Default6 READ default6)
    bool default6() const;

    Q_PROPERTY(QList<QDBusObjectPath> Devices READ devices)
    QList<QDBusObjectPath> devices() const;

    Q_PROPERTY(QDBusObjectPath Dhcp4Config READ dhcp4Config)
    QDBusObjectPath dhcp4Config() const;

    Q_PROPERTY(QDBusObjectPath Dhcp6Config READ dhcp6Config)
    QDBusObjectPath dhcp6Config() const;

    Q_PROPERTY(QString Id READ id)
    QString id() const;

    Q_PROPERTY(QDBusObjectPath Ip4Config READ ip4Config)
    QDBusObjectPath ip4Config() const;

    Q_PROPERTY(QDBusObjectPath Ip6Config READ ip6Config)
    QDBusObjectPath ip6Config() const;

    Q_PROPERTY(QDBusObjectPath Master READ master)
    QDBusObjectPath master() const;

    Q_PROPERTY(QDBusObjectPath SpecificObject READ specificObject)
    QDBusObjectPath specificObject() const;

    Q_PROPERTY(uint State READ state)
    uint state() const;

    Q_PROPERTY(QString Type READ type)
    QString type() const;

    Q_PROPERTY(QString Uuid READ uuid)
    QString uuid() const;

    Q_PROPERTY(bool Vpn READ vpn)
    bool vpn() const;

public Q_SLOTS: // METHODS
Q_SIGNALS: // SIGNALS
    void PropertiesChanged();
    void StateChanged(uint state, uint reason);
};

#endif
