/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./networkmanager-qt/src/dbus/introspection/org.freedesktop.NetworkManager.AgentManager.xml -a ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.AgentManagerAdaptor -i ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.AgentManager.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ORG_FREEDESKTOP_NETWORKMANAGER_AGENTMANAGERADAPTOR_H
#define ORG_FREEDESKTOP_NETWORKMANAGER_AGENTMANAGERADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.AgentManager.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.freedesktop.NetworkManager.AgentManager
 */
class AgentManagerAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.freedesktop.NetworkManager.AgentManager")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.freedesktop.NetworkManager.AgentManager\">\n"
"    <method name=\"Register\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"identifier\"/>\n"
"    </method>\n"
"    <method name=\"RegisterWithCapabilities\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"identifier\"/>\n"
"      <arg direction=\"in\" type=\"u\" name=\"capabilities\"/>\n"
"    </method>\n"
"    <method name=\"Unregister\"/>\n"
"  </interface>\n"
        "")
public:
    AgentManagerAdaptor(QObject *parent);
    virtual ~AgentManagerAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void Register(const QString &identifier);
    void RegisterWithCapabilities(const QString &identifier, uint capabilities);
    void Unregister();
Q_SIGNALS: // SIGNALS
};

#endif
