/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./networkmanager-qt/src/dbus/introspection/org.freedesktop.NetworkManager.DnsManager.xml -a ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.DnsManagerAdaptor -i ./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.DnsManager.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./networkmanager-qt/toolGenerate/qdbusxml2cpp/org.freedesktop.NetworkManager.DnsManagerAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class DnsManagerAdaptor
 */

DnsManagerAdaptor::DnsManagerAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

DnsManagerAdaptor::~DnsManagerAdaptor()
{
    // destructor
}

NMVariantMapList DnsManagerAdaptor::configuration() const
{
    // get the value of property Configuration
    return qvariant_cast< NMVariantMapList >(parent()->property("Configuration"));
}

QString DnsManagerAdaptor::mode() const
{
    // get the value of property Mode
    return qvariant_cast< QString >(parent()->property("Mode"));
}

QString DnsManagerAdaptor::rcManager() const
{
    // get the value of property RcManager
    return qvariant_cast< QString >(parent()->property("RcManager"));
}

